--TPOF String Table
TPOFVERSION = "2.6"
TPOFDATE = "February 5, 2010"
BUILDOWNER = "SRI-Emperor"
BUILDSYSTEM = "Obelisk"
SYSTEMOS =  "Microsoft Windows 7 Professional x64 [Version 6.1.7600]"
SYSTEMSTATS = "Intel Core i7 @ 2.68 GHz, 12.00 GB RAM, 2x Nvidia Geforce GTX 260"
SUPPORT = "Windows XP/VISTA/7 x86/x64, Mac OS X Tiger/Leopard/Snow Leopard (Intel)"
ISDEV = "No"
COPYRIGHT = "Copyright Sub-Real Industries 2007-2010"
