--TPOF String Table
TPOFVERSION = "2.9 Beta"
TPOFDATE = "May 19, 2010"
BUILDOWNER = "Osiris"
BUILDSYSTEM = "Obelisk"
SYSTEMOS =  "Linux Mint 8 Helena - Kernel 2.6.31-20"
SYSTEMSTATS = "Intel Core i7 @ 2.68 GHz, 12.00 GB RAM, 2x Nvidia Geforce GTX 260"
SUPPORT = "Windows XP/Vista/7, Mac OS X Tiger/Leopard/Snow Leopard (Intel), Wine 1.1.4"
ISDEV = "No"
COPYRIGHT = "Copyright Xi Company 2007-2010"
