-- Slipstream: The Price of Freedom - Vaygr Upgrade Tables
-- Includes Heavy Battlecruiser and capital ship upgrades

aitrace("LOADING SLIPSTREAM VAYGR UPGRADE INFO")

rt_mothership = { 
    MOTHERSHIPHEALTHUPGRADE1, MOTHERSHIPHEALTHUPGRADE2, 
    MOTHERSHIPMAXSPEEDUPGRADE1, MOTHERSHIPMAXSPEEDUPGRADE2 
}

-- SLIPSTREAM: Enhanced capital ship upgrades (includes Heavy BCs)
rt_capital = { 
    SUPERCAPHEALTHUPGRADE1, SUPERCAPHEALTHUPGRADE2, 
    SUPERCAPSPEEDUPGRADE1, SUPERCAPSPEEDUPGRADE2 
}

rt_fighter = { 
    FIGHTERHEALTHUPGRADE1, FIGHTERHEALTHUPGRADE2 
}

rt_corvette = { 
    CORVETTEHEALTHUPGRADE1, CORVETTEHEALTHUPGRADE2 
}

rt_frigate = { 
    FRIGATEHEALTHUPGRADE1, FRIGATEHEALTHUPGRADE2 
}

rt_platform = { 
    PLATFORMHEALTHUPGRADE1, PLATFORMHEALTHUPGRADE2 
}

rt_collector = { 
    UTILITYHEALTHUPGRADE1, UTILITYHEALTHUPGRADE2 
}
