
aitrace("LOADING VAYGR UPGRADE INFO")

rt_mothership = {
	MOTHERSHIPHEALTHUPGRADE1,
	MOTHERSHIPHEALTHUPGRADE2,
	MOTHERSHIPMAXSPEEDUPGRADE1,
	MOTHERSHIPMAXSPEEDUPGRADE2,
}

rt_capital = {
	SUPERCAPHEALTHUPGRADE1,
	SUPERCAPHEALTHUPGRADE2,
	SUPERCAPSPEEDUPGRADE1,
	SUPERCAPSPEEDUPGRADE2,
}


rt_fighter = {
	
	FIGHTERHEALTHUPGRADE1,
	FIGHTERHEALTHUPGRADE2,
}

rt_corvette = {
	
	CORVETTEHEALTHUPGRADE1,
	CORVETTEHEALTHUPGRADE2
}

rt_frigate = {
	FRIGATEHEALTHUPGRADE1,
	FRIGATEHEALTHUPGRADE2,
}

rt_platform = {
	PLATFORMHEALTHUPGRADE1,
	PLATFORMHEALTHUPGRADE2,
}

rt_collector = {
	UTILITYHEALTHUPGRADE1,
	UTILITYHEALTHUPGRADE2,
}

--rt_refinery = {
--	RESOURCECONTROLLERHEALTHUPGRADE1,
--	RESOURCECONTROLLERHEALTHUPGRADE2,
--}

--rt_hyperspace = {
--	cost = {
--		HYPERSPACECOSTUPGRADE1,
--		HYPERSPACECOSTUPGRADE2,
--	},
--	transittime = {
--		HYPERSPACETRANSITTIMEUPGRADE1,
--		HYPERSPACETRANSITTIMEUPGRADE2,
--	},
--	recoverytime = {
--		HYPERSPACERECOVERYTIMEUPGRADE1,
--		HYPERSPACERECOVERYTIMEUPGRADE2,
--	},
--}





