Modifier = 0
Ability = 1
Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
AllShips = 0
Family = 1
Ship = 2

research =
{
	{
		--Class Tech (INSTANT!)
		Name = "CorvetteTech",  
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7176",
		DisplayPriority = 20,
		Description = "$7177",
		TargetType = Family,
		TargetName = "Corvette",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7180",
	},
	{
		Name = "FrigateTech",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7178",
		DisplayPriority = 20,
		Description = "$7179",
		TargetType = Family,
		TargetName = "Frigate",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7181",
	},
	--Special Probes Tech
	{
		Name = "ProbeSensorDisruption",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 200,
		Time = 20,
		DisplayedName = "$7700",
		DisplayPriority = 210,
		Description = "$7701",
		TargetName = "Vgr_Probe_ECM",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7182",
	},
	{
		Name = "ProbeProxSensor",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 200,
		Time = 23,
		DisplayedName = "$7183",
		DisplayPriority = 220,
		Description = "$7184",
		TargetName = "Vgr_Probe_Prox",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7185",
	},
	--Special Fighter Tech
	{
		Name = "LanceBeams",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FighterProduction",
		Cost = 250,
		Time = 25,
		DisplayedName = "$7704",
		DisplayPriority = 220,
		Description = "$7705",
		TargetName = "Vgr_LanceFighter",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7301",
	},
	{
		Name = "PlasmaBombs",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FighterProduction",
		Cost = 300,
		Time = 30,
		DisplayedName = "$7702",
		DisplayPriority = 221,
		Description = "$7703",
		TargetName = "Vgr_Bomber",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7300",
	},
	--Special Corvette Tech
	{
		Name = "CorvetteGraviticAttraction",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CorvetteProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7706",
		DisplayPriority = 230,
		Description = "$7707",
		TargetName = "Vgr_MinelayerCorvette",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7302",
	},
	{
		Name = "CorvetteLaser",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CorvetteProduction",
		Cost = 400,
		Time = 40,
		DisplayedName = "$7708",
		DisplayPriority = 231,
		Description = "$7709",
		TargetName = "Vgr_LaserCorvette",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7303",
	},
	{
		Name = "CorvetteCommand",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CorvetteProduction",
		Cost = 420,
		Time = 42,
		DisplayedName = "$7710",
		DisplayPriority = 232,
		Description = "$7711",
		TargetName = "Vgr_CommandCorvette",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7304",
	},
	--Special Frigate Tech
	{
		Name = "FrigateAssault",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FrigateProduction",
		Cost = 450,
		Time = 45,
		DisplayedName = "$7714",
		DisplayPriority = 250,
		Description = "$7715",
		TargetName = "Vgr_AssaultFrigate",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7306",
	},
	{
		Name = "FrigateInfiltrationTech",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FrigateProduction",
		Cost = 500,
		Time = 40,
		DisplayedName = "$7716",
		DisplayPriority = 252,
		Description = "$7717",
		TargetName = "Vgr_InfiltratorFrigate",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7307",
	},
	--Special Super-Cap Tech
	{
		Name = "BattlecruiserIonWeapons",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CapShipProduction",
		Cost = 1000,
		Time = 60,
		DisplayedName = "$7718",
		DisplayPriority = 1,
		Description = "$7719",
		TargetName = "Vgr_BattleCruiser",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7308",
	},
	{
		Name = "DestroyerGuns",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CapShipProduction",
		Cost = 750,
		Time = 50,
		DisplayedName = "$7720",
		DisplayPriority = 261,
		Description = "$7721",
		TargetName = "Vgr_Destroyer",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7309",
	},
	{
		Name = "AncientHullEngineering",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CapShipProduction",
		Cost = 1250,
		Time = 75,
		DisplayedName = "Ancient Hull Engineering",
		DisplayPriority = 263,
		Description = "Configures Contruction bays to recreate Ancient Technology, and Fuse it with Dominion Engineering and Control Conduits.",
		TargetName = "Vgr_Dreadnaught",
		Icon = Icon_Tech,
		ShortDisplayedName = "Adv. Hull Engineering",
	},
	--Special Platform Tech
	{
		Name = "HyperspaceGateTech",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 300,
		Time = 40,
		DisplayedName = "$7722",
		DisplayPriority = 264,
		Description = "$7723",
		TargetName = "Vgr_HyperSpace_Platform",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7310",
	},
	{
		Name = "PlatformHeavyMissiles",
		RequiredResearch = "",
		RequiredSubSystems = "Research & PlatformProduction",
		Cost = 200,
		Time = 30,
		DisplayedName = "$7712",
		DisplayPriority = 240,
		Description = "$7713",
		TargetName = "Vgr_WeaponPlatform_missile",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7305",
	},
	--Special Utility Tech
	{
		Name = "RepairAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 500,
		Time = 30,
		DisplayedName = "$7724",
		DisplayPriority = 280,
		Description = "$7725",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Vgr_ResourceCollector",
		UpgradeName = "Repair",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7311",
	},
	{
		Name = "ScoutEMPAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FighterProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7732",
		DisplayPriority = 281,
		Description = "$7734",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Vgr_Scout",
		UpgradeName = "SpecialAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7314",
	},
	{
		Name = "BomberImprovedBombs",
		RequiredResearch = "PlasmaBombs",
		RequiredSubSystems = "Research",
		Cost = 1500,
		Time = 45,
		DisplayedName = "$7730",
		DisplayPriority = 282,
		Description = "$7731",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Vgr_Bomber",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7313",
	},
	{
		Name = "MothershipBUILDSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7815",
		DisplayPriority = 45,
		Description = "$7816",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_MotherShip",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "$7240",
	},
	
	--Fighter Upgrades
	{
		Name = "FighterSpeedUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "FighterProduction & Research",
		Cost = 150,
		Time = 50,
		DisplayedName = "+5% Fighter Speed",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Fighter conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Family, 
		TargetName = "Fighter", 
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	
	{
		Name = "FighterHealthUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FighterProduction",
		Cost = 250,
		Time = 45,
		DisplayedName = "+10% Drone Health",
		DisplayPriority = 82,
		Description = "<b>Description:</b> Improves Fighter Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Family, 
		TargetName = "Fighter", 
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	
	{
		Name = "FighterWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research & FighterProduction",
		Cost = 250,
		Time = 40,
		DisplayedName = "+5% DroneWeapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Fighter Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Family, 
		TargetName = "Fighter", 
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "FighterWeaponUpgradePartTwo",
		RequiredResearch = "DroneWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Family, 
		TargetName = "Fighter", 
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	
	--Corvette Upgrades
	{
		Name = "CorvetteHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "CorvetteProduction & Research",
		Cost = 900,
		Time = 60,
		DisplayedName = "+10% Corvette Health",
		DisplayPriority = 200,
		Description = "<b>Description:</b> Improves Corvette Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.10,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "CorvetteHealthUpgrade2",
		RequiredResearch = "CorvetteHealthUpgrade1",
		RequiredSubSystems = "CorvetteProduction & Research",
		Cost = 1800,
		Time = 80,
		DisplayedName = "+5% Corvette Health",
		DisplayPriority = 200,
		Description = "<b>Description:</b> Improves Corvette Hulls by an additional 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	{
		Name = "CorvetteSpeedUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "CorvetteProduction & Research",
		Cost = 800,
		Time = 60,
		DisplayedName = "+15% Corvette Speed",
		DisplayPriority = 201,
		Description = "<b>Description:</b> Improves Corvette conventional drive systems by 15%. \n\n<b>Prerequisites:</b> Technology Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.15,
		Icon = Icon_Speed,
		ShortDisplayedName = "+15% MaxSpeed",
	},
	{
		Name = "CorvetteSpeedUpgrade2",
		RequiredResearch = "CorvetteSpeedUpgrade1",
		RequiredSubSystems = "CorvetteProduction & Research",
		Cost = 1600,
		Time = 80,
		DisplayedName = "+5% Corvette Speed",
		DisplayPriority = 201,
		Description = "<b>Description:</b> Improves Corvette conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.20,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	
	{
		Name = "CorvetteWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Assault Corvette Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Corvette Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "CorvetteWeaponUpgradePartTwo",
		RequiredResearch = "CorvetteWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Frigate Upgrades
	{
		Name = "FrigateHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "FrigateProduction & Research",
		Cost = 1600,
		Time = 80,
		DisplayedName = "+18% Frigate Health",
		DisplayPriority = 306,
		Description = "<b>Description:</b> Improves Frigate Hulls by 18%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.18,
		Icon = Icon_Health,
		ShortDisplayedName = "+18% Health",
	},
	{
		Name = "FrigateHealthUpgrade2",
		RequiredResearch = "FrigateHealthUpgrade1",
		RequiredSubSystems = "FrigateProduction & Research",
		Cost = 1000,
		Time = 100,
		DisplayedName = "+2% Frigate Health",
		DisplayPriority = 306,
		Description = "<b>Description:</b> Improves Frigate Hulls by an additional 2%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.20,
		Icon = Icon_Health,
		ShortDisplayedName = "+2% Health",
	},
	{
		Name = "FrigateSpeedUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "FrigateProduction & Research",
		Cost = 1000,
		Time = 70,
		DisplayedName = "+4% Frigate Speed",
		DisplayPriority = 307,
		Description = "<b>Description:</b> Improves Frigate conventional drive systems by 4%. \n\n<b>Prerequisites:</b> Technology Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.04,
		Icon = Icon_Speed,
		ShortDisplayedName = "+4% MaxSpeed",
	},
	{
		Name = "FrigateSpeedUpgrade2",
		RequiredResearch = "FrigateSpeedUpgrade1",
		RequiredSubSystems = "FrigateProduction & Research",
		Cost = 1500,
		Time = 100,
		DisplayedName = "+6% Frigate Speed",
		DisplayPriority = 307,
		Description = "<b>Description:</b> Improves Frigate conventional drive systems by 6%. \n\n<b>Prerequisites:</b> Technology Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	
	{
		Name = "FrigateWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+14% Frigate Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Frigate Weapon systems by 14%. \n\n<b>Prerequisites:</b> Technology Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "+14% Weapons",
	},
	{
		Name = "FrigateWeaponUpgradePartTwo",
		RequiredResearch = "FrigateWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Capital Upgrades
	
	{
		Name = "SuperCapHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "CapShipProduction & Research",
		Cost = 4000,
		Time = 60,
		DisplayedName = "+20% Super Capital Health",
		DisplayPriority = 61,
		Description = "<b>Description:</b> Improves Super Capital speed by 20%, allowing them to move faster. \n\n<b>Prerequisites:</b> Technology Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.2,
		Icon = Icon_Health,
		ShortDisplayedName = "+20% Health",
	},
	{
		Name = "SuperCapHealthUpgrade2",
		RequiredResearch = "SuperCapHealthUpgrade1",
		RequiredSubSystems = "CapShipProduction & Research",
		Cost = 6000,
		Time = 80,
		DisplayedName = "+5% Super Capital Health",
		DisplayPriority = 61,
		Description = "<b>Description:</b> Improves Super Capital speed by an additional 5%, allowing them to move faster. \n\n<b>Prerequisites:</b> Technology Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.25,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	{
		Name = "SuperCapSpeedUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "CapShipProduction & Research",
		Cost = 3500,
		Time = 60,
		DisplayedName = "+20% Super Capital Speed",
		DisplayPriority = 64,
		Description = "<b>Description:</b> Improves Super Capital speed by 20%, allowing them to move faster. \n\n<b>Prerequisites:</b> Technology Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "+20% MaxSpeed",
	},
	{
		Name = "SuperCapSpeedUpgrade2",
		RequiredResearch = "SuperCapSpeedUpgrade1",
		RequiredSubSystems = "CapShipProduction & Research",
		Cost = 5000,
		Time = 80,
		DisplayedName = "+5% Super Capital Speed",
		DisplayPriority = 64,
		Description = "<b>Description:</b> Improves Super Capital speed by an additional 5%, allowing them to move faster. \n\n<b>Prerequisites:</b> Technology Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	
	{
		Name = "SuperCapWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "CapShipProduction & Research",
		Cost = 3000,
		Time = 100,
		DisplayedName = "+5% Super Capital Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Super Capital Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "SuperCapWeaponUpgradePartTwo",
		RequiredResearch = "SuperCapWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	{
		Name = "CarrierBUILDSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research & CapShipProduction",
		Cost = 1500,
		Time = 100,
		DisplayedName = "-10% Super Capital Build Time",
		DisplayPriority = 65,
		Description = "<b>Description:</b> Allows Super Capitals to Build ships 10% Faster. \n\n<b>Prerequisites:</b> Technology Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Build,
		ShortDisplayedName = "-10% Build Time",
	},
	
	--Platform Upgrades
	{
		Name = "PlatformHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "PlatformProduction & Research",
		Cost = 500,
		Time = 50,
		DisplayedName = "+10% Platform Health",
		DisplayPriority = 600,
		Description = "<b>Description:</b> Improves Platform Health by 10%. \n\n<b>Prerequisites:</b> Technology Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Platform",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.10,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "PlatformHealthUpgrade2",
		RequiredResearch = "PlatformHealthUpgrade1",
		RequiredSubSystems = "PlatformProduction & Research",
		Cost = 600,
		Time = 70,
		DisplayedName = "+10% Platform Health",
		DisplayPriority = 600,
		Description = "<b>Description:</b> Improves Platform Health by an additional 5%. \n\n<b>Prerequisites:</b> Technology Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Platform",
		UpgradeName = "MAXHEALTH",
		UpgradeValue =1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	
	{
		Name = "PlatformWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Platform Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Platform Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Platform",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "PlatformWeaponUpgradePartTwo",
		RequiredResearch = "PlatformWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Platform",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Utility Upgrades
	{
		Name = "UtilityHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 1200,
		Time = 50,
		DisplayedName = "+10% Utility Health",
		DisplayPriority = 701,
		Description = "<b>Description:</b> Improves Platform Health by 10%. \n\n<b>Prerequisites:</b> Technology Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Utility",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.10,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "UtilityHealthUpgrade2",
		RequiredResearch = "UtilityHealthUpgrade1",
		RequiredSubSystems = "Research",
		Cost = 2400,
		Time = 70,
		DisplayedName = "+5% Utility Health",
		DisplayPriority = 701,
		Description = "<b>Description:</b> Improves Platform Health by an additional 5%. \n\n<b>Prerequisites:</b> Technology Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Utility",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "++5% Health",
	},
	--SP Cracks
	{
		Name = "WeakVgrHeavyMissiles",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Reduces damage on Vgr Heavy Missiles (SP Game only!)",
		DisplayPriority = 1205,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_HeavyMissileFrigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.25,
	},
	{
		Name = "HyperspaceRecoveryTimeUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Hyperspace Recovery - SP GAME ONLY",
		DisplayPriority = 1206,
		Description = "",
		UpgradeType = Modifier,
		TargetType = AllShips,
		UpgradeName = "HyperspaceRecoveryTime",
		UpgradeValue = 0.01,
	},
	{
		Name = "VaygrCarrierHealthRegenDowngrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vaygr Carrier Health Regen Rate Downgrade",
		DisplayPriority = 1207,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_Carrier",
		UpgradeName = "HealthRegenerationRate",
		UpgradeValue = 0.1,
	},
	{
		Name = "HyperspaceTransitionTimeUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Hyperspace Transition - SP GAME ONLY",
		DisplayPriority = 1206,
		Description = "",
		UpgradeType = Modifier,
		TargetType = AllShips,
		UpgradeName = "HyperspaceTime",
		UpgradeValue = 0.1,
	},
	{
		Name = "SuperCapHealthUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vgr Super Cap Health Upgrade",
		DisplayPriority = 1208,
		Description = "Vaygr Carrier Health upgrade - SP GAME ONLY",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Capital",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3.5,
	},
	{
		Name = "ShipyardSpeedDowngradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vaygr Shipyard Speed downgrade",
		DisplayPriority = 1208,
		Description = "Vaygr Shipyard Speed downgrade - SP GAME ONLY",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_ShipYard",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 0.0001,
	},
	{
		Name = "VaygrFrigateHealthUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vgr Frigate Health Upgrade",
		DisplayPriority = 1208,
		Description = "Vaygr Frigate Health upgrade - SP GAME ONLY",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3,
	},
	{
		Name = "VaygrFrigateHealthRegenDowngradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vaygr Frigate Health Regen Rate Downgrade",
		DisplayPriority = 1207,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "HealthRegenerationRate",
		UpgradeValue = 0.1,
	},
	{
		Name = "CorvetteHealthUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vgr Corvette Health Upgrade",
		DisplayPriority = 1208,
		Description = "Vaygr Corvette Health upgrade - SP GAME ONLY",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Corvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3.5,
	},
	{
		Name = "ExtraStrongVgrHeavyMissilesSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Increases damage on Vgr Heavy Missiles (SP Game only!)",
		DisplayPriority = 1205,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_HeavyMissileFrigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.35,
	},
	{
		Name = "VaygrCaptureHack",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Increases Capture Speed (SP Game only!)",
		DisplayPriority = 1205,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_InfiltratorFrigate",
		UpgradeName = "Capture",
		UpgradeValue = 1.35,
	},
	{
		Name = "VaygrReduceCaptureHack",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Increases Capture Speed (SP Game only!)",
		DisplayPriority = 1205,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_InfiltratorFrigate",
		UpgradeName = "Capture",
		UpgradeValue = 0.75,
	},
	{
		Name = "VaygrRadiationImmunityHack",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Makes Vaygr Immune to Radiation (SP Game only!)",
		DisplayPriority = 1205,
		Description = "",
		UpgradeType = Modifier,
		TargetType = AllShips,
		UpgradeName = "NebulaSensitivity",
		UpgradeValue = 0,
	},
	{
		Name = "VaygrCarrierHealthUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Vaygr Carrier Health Upgrade",
		DisplayPriority = 1208,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_Carrier",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3,
	},
	--Custom Hooks
	{
		Name = "SYENABLED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Enables/Disables the shipyard",
		DisplayPriority = 1208,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Vgr_Shipyard",
		Icon = Icon_Tech,
		ShortDisplayedName = "SYENABLED",
	},
}
