-- LuaDC version 0.9.20
-- 11/4/2024 10:16:15 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
Ship = 0
SubSystem = 1
build =
{
    -- Weapons
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_missileboxturret_1",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1000,
        DisplayedName = "$2048",
        Description = "$2049",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_missileboxturret_2",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1010,
        DisplayedName = "$2048",
        Description = "$2049",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_pulsecannonturret_1",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1100,
        DisplayedName = "$2028",
        Description = "$2027",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_pulsecannonturret_2",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1110,
        DisplayedName = "$2028",
        Description = "$2027",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_rapidlaserturret_1",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1200,
        DisplayedName = "$2044",
        Description = "$2049",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_rapidlaserturret_2",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1210,
        DisplayedName = "$2044",
        Description = "$2049",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_scattershotturret_1",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1300,
        DisplayedName = "$2046",
        Description = "$2047",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_dd_scattershotturret_2",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1310,
        DisplayedName = "$2046",
        Description = "$2047",
    },
    -- Vaygr Battlecruiser Missile Battery variants
    {
        Type = SubSystem,
        ThingToBuild = "vgr_bc_heavyfusionmissile",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1400,
        DisplayedName = "$8004",
        Description = "$8005",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_bc_sunshattermissile",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1410,
        DisplayedName = "$8002",
        Description = "$8003",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_bc_swarmmissile",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1420,
        DisplayedName = "$8006",
        Description = "$8007",
    },
    {
        Type = SubSystem,
        ThingToBuild = "vgr_bc_concussionmissile",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 1430,
        DisplayedName = "$8000",
        Description = "$8001",
    },
    -- Subsystems
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Module_CloakGenerator",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 15,
        DisplayedName = "$7118",
        Description = "$7119",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Module_HyperspaceInhibitor",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 16,
        DisplayedName = "$7116",
        Description = "$7117",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Module_FireControl",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 21,
        DisplayedName = "$7120",
        Description = "$7121",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Module_Hyperspace",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 20,
        DisplayedName = "$7114",
        Description = "$7115",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Sensors_AdvancedArray",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 25,
        DisplayedName = "$7122",
        Description = "$7123",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Sensors_DetectHyperspace",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 30,
        DisplayedName = "$7126",
        Description = "$7127",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Sensors_DetectCloaked",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 40,
        DisplayedName = "$7024",
        Description = "$7025",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Sensors_Distortion",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 50,
        DisplayedName = "$8009",
        Description = "$8010",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Module_BuildSpeed",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 70,
        DisplayedName = "$8011",
        Description = "$8012",
    },
    {
        Type = SubSystem,
        ThingToBuild = "Vgr_C_Module_MaxSpeed",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 80,
        DisplayedName = "$8013",
        Description = "$8014",
    },
    -- Ships
    {
        Type = Ship,
        ThingToBuild = "Vgr_Interceptor",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 21,
        DisplayedName = "$7132",
        Description = "$7133",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_Bomber",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 22,
        DisplayedName = "$7134",
        Description = "$7135",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_LanceFighter",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 23,
        DisplayedName = "$7136",
        Description = "$7137",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_MissileCorvette",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 100,
        DisplayedName = "$7138",
        Description = "$7139",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_LaserCorvette",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 105,
        DisplayedName = "$7140",
        Description = "$7141",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_AssaultFrigate",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 220,
        DisplayedName = "$7146",
        Description = "$7147",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_HeavyMissileFrigate",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 200,
        DisplayedName = "$7148",
        Description = "$7149",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_Destroyer",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 300,
        DisplayedName = "$7152",
        Description = "$7153",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_BattleCruiser",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 330,
        DisplayedName = "$7158",
        Description = "$7159",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_ResourceCollector",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 500,
        DisplayedName = "$7164",
        Description = "$7165",
    },
    {
        Type = Ship,
        ThingToBuild = "Vgr_ResourceController",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 510,
        DisplayedName = "$7166",
        Description = "$7167",
    },
}
