-- LuaDC version 0.9.20
-- 12/20/2025 8:42:15 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
Modifier = 0
Ability = 1
Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
AllShips = 0
Family = 1
Ship = 2
research =
{
    {
        Name = "SuperCapHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 4000,
        Time = 60,
        DisplayedName = "$7743",
        DisplayPriority = 61,
        Description = "$7744",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Capital",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7354",
    },
    {
        Name = "SuperCapHealthUpgrade2",
        RequiredResearch = "SuperCapHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 6000,
        Time = 80,
        DisplayedName = "$7745",
        DisplayPriority = 61,
        Description = "$7746",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Capital",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7355",
    },
    {
        Name = "SuperCapSpeedUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 3500,
        Time = 60,
        DisplayedName = "$7747",
        DisplayPriority = 64,
        Description = "$7748",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Capital",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7354",
    },
    {
        Name = "SuperCapSpeedUpgrade2",
        RequiredResearch = "SuperCapSpeedUpgrade1",
        RequiredSubSystems = "",
        Cost = 5000,
        Time = 80,
        DisplayedName = "$7749",
        DisplayPriority = 64,
        Description = "$7750",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Capital",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7355",
    },
    {
        Name = "FighterspeedUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 600,
        Time = 50,
        DisplayedName = "$7755",
        DisplayPriority = 81,
        Description = "$7756",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Fighter",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.25,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7331",
    },
    {
        Name = "FighterspeedUpgrade2",
        RequiredResearch = "FighterspeedUpgrade1",
        RequiredSubSystems = "",
        Cost = 1000,
        Time = 70,
        DisplayedName = "$7757",
        DisplayPriority = 81,
        Description = "$7758",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Fighter",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.5,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7332",
    },
    {
        Name = "CorvetteHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 900,
        Time = 60,
        DisplayedName = "$7759",
        DisplayPriority = 200,
        Description = "$7760",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Corvette",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7341",
    },
    {
        Name = "CorvetteHealthUpgrade2",
        RequiredResearch = "CorvetteHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 1800,
        Time = 80,
        DisplayedName = "$7761",
        DisplayPriority = 200,
        Description = "$7762",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Corvette",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7342",
    },
    {
        Name = "CorvetteSpeedUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 800,
        Time = 60,
        DisplayedName = "$7763",
        DisplayPriority = 201,
        Description = "$7764",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Corvette",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7341",
    },
    {
        Name = "CorvetteSpeedUpgrade2",
        RequiredResearch = "CorvetteSpeedUpgrade1",
        RequiredSubSystems = "",
        Cost = 1600,
        Time = 80,
        DisplayedName = "$7765",
        DisplayPriority = 201,
        Description = "$7766",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Corvette",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.4,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7342",
    },
    {
        Name = "FrigateHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 1600,
        Time = 80,
        DisplayedName = "$7767",
        DisplayPriority = 306,
        Description = "$7768",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Frigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7371",
    },
    {
        Name = "FrigateHealthUpgrade2",
        RequiredResearch = "FrigateHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 2800,
        Time = 100,
        DisplayedName = "$7769",
        DisplayPriority = 306,
        Description = "$7770",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Frigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7372",
    },
    {
        Name = "FrigateSpeedUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 1000,
        Time = 70,
        DisplayedName = "$7771",
        DisplayPriority = 307,
        Description = "$7772",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Frigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7371",
    },
    {
        Name = "SpeedUpgrade2",
        RequiredResearch = "FrigateSpeedUpgrade1",
        RequiredSubSystems = "",
        Cost = 1500,
        Time = 100,
        DisplayedName = "$7773",
        DisplayPriority = 307,
        Description = "$7774",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Frigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7372",
    },
    {
        Name = "UtilityHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 1200,
        Time = 50,
        DisplayedName = "$7779",
        DisplayPriority = 701,
        Description = "$7780",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Utility",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.5,
        Icon = Icon_Health,
        ShortDisplayedName = "$7351",
    },
    {
        Name = "UtilityHealthUpgrade2",
        RequiredResearch = "UtilityHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 2400,
        Time = 70,
        DisplayedName = "$7781",
        DisplayPriority = 701,
        Description = "$7782",
        UpgradeType = Modifier,
        TargetType = Family,
        TargetName = "Utility",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 2,
        Icon = Icon_Health,
        ShortDisplayedName = "$7352",
    },
}
