-- LuaDC version 0.9.19
-- 5/23/2004 7:23:49 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
UC_Family("Fighter", 8)
UC_FamilyOverride("Vaygr", "Fighter", 10)
UC_Family("Corvette", 8)
UC_ShipType("MinelayerCorvette", 2)
UC_Family("Frigate", 12)
UC_ShipType("DefenseFieldFrigate", 2)
UC_ShipType("CaptureFrigate", 6)
UC_ShipTypeOverride("Hiigaran", "CaptureFrigate", 4)
UC_Family("Capital", 10)
UC_FamilyOverride("Vaygr", "Capital", 12)
UC_ShipType("Destroyer", 3)
UC_ShipType("Carrier", 4)
UC_ShipTypeOverride("Vaygr", "Carrier", 6)
UC_ShipType("Battlecruiser", 2)
UC_ShipType("Shipyard", 1)
UC_Family("Utility", 42)
UC_ShipType("ResourceCollector", 20)
UC_ShipType("ResourceController", 4)
UC_ShipType("Probe", 6)
UC_ShipType("ECMProbe", 6)
UC_ShipType("ProximitySensor", 6)
UC_Family("Platform", 14)
UC_ShipType("HyperspacePlatform", 4)
UC_Family("Mothership", 6)
UC_Family("SinglePlayerMisc", 100)
