-- LuaDC version 0.9.20
-- 12/20/2025 8:42:15 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2
research =

{
    {
        Name = "InterceptorMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 300,
        Time = 30,
        DisplayedName = "$7543",
        DisplayPriority = 81,
        Description = "$7544",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_Interceptor",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.25,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7231",
    },
    {
        Name = "InterceptorMAXSPEEDUpgrade2",
        RequiredResearch = "InterceptorMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 40,
        DisplayedName = "$7545",
        DisplayPriority = 81,
        Description = "$7546",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_Interceptor",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.5,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7232",
    },
    {
        Name = "AssaultCorvetteHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 40,
        DisplayedName = "$7555",
        DisplayPriority = 200,
        Description = "$7556",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultCorvette",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7237",
    },
    {
        Name = "AssaultCorvetteHealthUpgrade2",
        RequiredResearch = "AssaultCorvetteHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 750,
        Time = 50,
        DisplayedName = "$7557",
        DisplayPriority = 200,
        Description = "$7558",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultCorvette",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7238",
    },
    {
        Name = "AssaultCorvetteMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 300,
        Time = 40,
        DisplayedName = "$7559",
        DisplayPriority = 203,
        Description = "$7560",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultCorvette",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7237",
    },
    {
        Name = "AssaultCorvetteMAXSPEEDUpgrade2",
        RequiredResearch = "AssaultCorvetteMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 50,
        DisplayedName = "$7561",
        DisplayPriority = 203,
        Description = "$7562",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultCorvette",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7238",
    },
    {
        Name = "PulsarCorvetteHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 400,
        Time = 40,
        DisplayedName = "$7563",
        DisplayPriority = 206,
        Description = "$7564",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_PulsarCorvette",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7241",
    },
    {
        Name = "PulsarCorvetteHealthUpgrade2",
        RequiredResearch = "PulsarCorvetteHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 750,
        Time = 50,
        DisplayedName = "$7565",
        DisplayPriority = 206,
        Description = "$7566",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_PulsarCorvette",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7242",
    },
    {
        Name = "PulsarCorvetteMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 300,
        Time = 40,
        DisplayedName = "$7567",
        DisplayPriority = 209,
        Description = "$7568",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_PulsarCorvette",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7241",
    },
    {
        Name = "PulsarCorvetteMAXSPEEDUpgrade2",
        RequiredResearch = "PulsarCorvetteMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 750,
        Time = 50,
        DisplayedName = "$7569",
        DisplayPriority = 209,
        Description = "$7570",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_PulsarCorvette",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7242",
    },
    {
        Name = "TorpedoFrigateHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 800,
        Time = 60,
        DisplayedName = "$7571",
        DisplayPriority = 300,
        Description = "$7572",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_TorpedoFrigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7244",
    },
    {
        Name = "TorpedoFrigateHealthUpgrade2",
        RequiredResearch = "TorpedoFrigateHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 1400,
        Time = 75,
        DisplayedName = "$7573",
        DisplayPriority = 300,
        Description = "$7574",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_TorpedoFrigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7245",
    },
    {
        Name = "TorpedoFrigateMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 50,
        DisplayedName = "$7575",
        DisplayPriority = 303,
        Description = "$7576",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_TorpedoFrigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7244",
    },
    {
        Name = "TorpedoFrigateMAXSPEEDUpgrade2",
        RequiredResearch = "TorpedoFrigateMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 750,
        Time = 70,
        DisplayedName = "$7577",
        DisplayPriority = 303,
        Description = "$7578",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_TorpedoFrigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7245",
    },
    {
        Name = "IonCannonFrigateHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 800,
        Time = 60,
        DisplayedName = "$7579",
        DisplayPriority = 306,
        Description = "$7580",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_IonCannonFrigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7247",
    },
    {
        Name = "IonCannonFrigateHealthUpgrade2",
        RequiredResearch = "IonCannonFrigateHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 1400,
        Time = 75,
        DisplayedName = "$7581",
        DisplayPriority = 306,
        Description = "$7582",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_IonCannonFrigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7248",
    },
    {
        Name = "IonCannonFrigateMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 50,
        DisplayedName = "$7583",
        DisplayPriority = 309,
        Description = "$7584",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_IonCannonFrigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7247",
    },
    {
        Name = "IonCannonFrigateMAXSPEEDUpgrade2",
        RequiredResearch = "IonCannonFrigateMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 750,
        Time = 70,
        DisplayedName = "$7585",
        DisplayPriority = 309,
        Description = "$7586",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_IonCannonFrigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7248",
    },
    {
        Name = "AssaultFrigateHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 800,
        Time = 60,
        DisplayedName = "$7587",
        DisplayPriority = 312,
        Description = "$7588",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultFrigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7251",
    },
    {
        Name = "AssaultFrigateHealthUpgrade2",
        RequiredResearch = "AssaultFrigateHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 1400,
        Time = 75,
        DisplayedName = "$7589",
        DisplayPriority = 312,
        Description = "$7590",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultFrigate",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7252",
    },
    {
        Name = "AssaultFrigateMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 50,
        DisplayedName = "$7591",
        DisplayPriority = 315,
        Description = "$7592",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultFrigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7251",
    },
    {
        Name = "AssaultFrigateMAXSPEEDUpgrade2",
        RequiredResearch = "AssaultFrigateMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 750,
        Time = 70,
        DisplayedName = "$7593",
        DisplayPriority = 315,
        Description = "$7594",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_AssaultFrigate",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7252",
    },
    {
        Name = "BattlecruiserHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 2000,
        Time = 60,
        DisplayedName = "$7595",
        DisplayPriority = 401,
        Description = "$7596",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_BattleCruiser",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7254",
    },
    {
        Name = "BattlecruiserHealthUpgrade2",
        RequiredResearch = "BattlecruiserHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 3000,
        Time = 75,
        DisplayedName = "$7597",
        DisplayPriority = 401,
        Description = "$7598",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_BattleCruiser",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7255",
    },
    {
        Name = "BattlecruiserMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 1000,
        Time = 30,
        DisplayedName = "$7599",
        DisplayPriority = 404,
        Description = "$7600",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_BattleCruiser",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7254",
    },
    {
        Name = "BattlecruiserMAXSPEEDUpgrade2",
        RequiredResearch = "BattlecruiserMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 1500,
        Time = 40,
        DisplayedName = "$7601",
        DisplayPriority = 404,
        Description = "$7602",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_BattleCruiser",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7255",
    },
    {
        Name = "DestroyerHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 1000,
        Time = 60,
        DisplayedName = "$7639",
        DisplayPriority = 405,
        Description = "$7640",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_Destroyer",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        ShortDisplayedName = "$7274",
        Icon = Icon_Health,
    },
    {
        Name = "DestroyerHealthUpgrade2",
        RequiredResearch = "DestroyerHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 1500,
        Time = 75,
        DisplayedName = "$7641",
        DisplayPriority = 405,
        Description = "$7642",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_Destroyer",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7275",
    },
    {
        Name = "DestroyerMAXSPEEDUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 1000,
        Time = 30,
        DisplayedName = "$7643",
        DisplayPriority = 406,
        Description = "$7644",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_Destroyer",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.2,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7274",
    },
    {
        Name = "DestroyerMAXSPEEDUpgrade2",
        RequiredResearch = "DestroyerMAXSPEEDUpgrade1",
        RequiredSubSystems = "",
        Cost = 1500,
        Time = 40,
        DisplayedName = "$7645",
        DisplayPriority = 406,
        Description = "$7646",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_Destroyer",
        UpgradeName = "MAXSPEED",
        UpgradeValue = 1.35,
        Icon = Icon_Speed,
        ShortDisplayedName = "$7275",
    },
    {
        Name = "ResourceCollectorHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 400,
        Time = 40,
        DisplayedName = "$7611",
        DisplayPriority = 701,
        Description = "$7612",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_ResourceCollector",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.5,
        Icon = Icon_Health,
        ShortDisplayedName = "$7264",
    },

    {
        Name = "ResourceCollectorHealthUpgrade2",
        RequiredResearch = "ResourceCollectorHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 800,
        Time = 60,
        DisplayedName = "$7613",
        DisplayPriority = 701,
        Description = "$7614",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_ResourceCollector",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 2,
        Icon = Icon_Health,
        ShortDisplayedName = "$7265",
    },
    {
        Name = "ResourceControllerHealthUpgrade1",
        RequiredResearch = "",
        RequiredSubSystems = "",
        Cost = 500,
        Time = 30,
        DisplayedName = "$7267",
        DisplayPriority = 704,
        Description = "$7616",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_ResourceController",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.3,
        Icon = Icon_Health,
        ShortDisplayedName = "$7267",
    },
    {
        Name = "ResourceControllerHealthUpgrade2",
        RequiredResearch = "ResourceControllerHealthUpgrade1",
        RequiredSubSystems = "",
        Cost = 1000,
        Time = 40,
        DisplayedName = "$7617",
        DisplayPriority = 704,
        Description = "$7618",
        UpgradeType = Modifier,
        TargetType = Ship,
        TargetName = "Hgn_ResourceController",
        UpgradeName = "MAXHEALTH",
        UpgradeValue = 1.6,
        Icon = Icon_Health,
        ShortDisplayedName = "$7268",
    },
}
