Ship = 0
SubSystem = 1

build =
{
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Production_Fighter",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		Description = "$7001",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_Fighter",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		Description = "$7001",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Production_Corvette",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		Description = "$7003",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_Corvette",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		Description = "$7003",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Production_Frigate",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		Description = "$7005",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_Frigate",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		Description = "$7005",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_CapShip",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		Description = "$7007",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_SY_Production_CapShip",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		Description = "$7007",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_PlatformControl",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 10,
		DisplayedName = "$7008",
		Description = "$7009",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_PlatformControl",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 20,
		DisplayedName = "$7008",
		Description = "$7009",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "Technology I Module",
		Description = "$7011",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "Technology I Module",
		Description = "$7011",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_ResearchAdvanced",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 10,
		DisplayedName = "Technology II Module",
		Description = "$7013",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_ResearchAdvanced",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 10,
		DisplayedName = "Technology II Module",
		Description = "$7013",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_Hyperspace",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 30,
		DisplayedName = "Slipstream Generator",
		Description = "<b>Description:</b>  Slipstream Generators and Field Projectors. Allows nearby Frigates and Capital ships to hyperspace. \n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b> Technology I Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_Hyperspace",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 30,
		DisplayedName = "Slipstream Generator",
		Description = "<b>Description:</b>  Slipstream Generators and Field Projectors allow nearby Frigates and Capital ships to hyperspace.\n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b> Technology I Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 40,
		DisplayedName = "Slipstream Negator",
		Description = "<b>Description:</b>  The UNCG were the first to invent the technology of destroying slipstreams. Even the Tsaraii did not have this ability (or did not use it). The Process involved creating electromagnetic turbulence, which will cause a slipstream to vaporize on formation.\n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b> Technology I Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 40,
		DisplayedName = "Slipstream Negator",
		Description = "<b>Description:</b>  The UNCG were the first to invent the technology of destroying slipstreams. Even the Tsaraii did not have this ability (or did not use it). The Process involved creating electromagnetic turbulence, which will cause a slipstream to vaporize on formation.\n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b> Technology I Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_CloakGenerator",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 50,
		DisplayedName = "Defence Field Generator",
		Description = "<b>Description:</b> The Ultimate in defense technology. The UNCG were able to create a generator that can deflect many weapon systems, a technology the DSCG has yet to master. \n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b> Technology I Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_CloakGenerator",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 50,
		DisplayedName = "Defence Field Generator",
		Description = "<b>Description:</b> The Ultimate in defense technology. The UNCG were able to create a generator that can deflect many weapon systems, a technology the DSCG has yet to master. \n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b> Technology I Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_FireControl",
		RequiredResearch = "",
		RequiredFleetSubSystems = "AdvancedResearch",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		Description = "$7021",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_FireControl",
		RequiredResearch = "",
		RequiredFleetSubSystems = "AdvancedResearch",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		Description = "$7021",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Sensors_DetectHyperspace",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		Description = "$7037",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Sensors_DetectHyperspace",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		Description = "$7037",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Sensors_AdvancedArray",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		Description = "$7023",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Sensors_AdvancedArray",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		Description = "$7023",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Sensors_DetectCloaked",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		Description = "$7025",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Sensors_DetectCloaked",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		Description = "$7025",
	},
	{
		Type = Ship,
		ThingToBuild = "Kpr_Mover",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 53,
		DisplayedName = "$7913",
		Description = "$7914",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_CorvetteMover",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 10,
		DisplayedName = "$7910",
		Description = "$7911",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Drone",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 5,
		DisplayedName = "Drone",
		Description = "<b>Type: Drone</b>\n<b>Description:</b>\n\nCheap Anti-Fighter Drone\n\n<b>Requires:</b>\nFighter Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Interceptor",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		DisplayPriority = 20,
		DisplayedName = "$7032",
		Description = "<b>Type: Medium Fighter</b>\n<b>Description:</b>\n\nThis fighter is built to take the extreme heat of capship combat, and the high speed turns of dogfights.\n\n<b>Requires:</b>\nFighter Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_AttackBomber",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		DisplayPriority = 30,
		DisplayedName = "Bomber",
		Description = "<b>Type: Medium Fighter</b>\n<b>Description:</b>\n\nThe Unmanned bomber got its name after it's debut battle when a prototype was used in the now infamous battle in the Solar System wars in which much UNCG technology was derived. A solution was needed to take care of frigates while using very little resources, and time. This came arise to mounting to plasma tubes on the the side of a experimental strike fighter drone with an oversized powerplant.\n\n<b>Requires:</b>\nFighter Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_AssaultCorvette",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 51,
		DisplayedName = "Assault Corvette",
		Description = "<b>Type: Standard Corvette</b>\n<b>Description:</b>\n\nThe Standard Corvette carries a small plasma gun capable of discharging high speed bolts to destroy fighters.\n\n<b>Requires:</b>\nCorvette Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_PulsarCorvette",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 52,
		DisplayedName = "Pulsar Corvette",
		Description = "<b>Type: Standard Corvette</b>\n<b>Description:</b>\n\nThis Corvette can fly around its target and fire a small laser into its side, devastating frigates.\n\n<b>Requires:</b>\nCorvette Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_minelayercorvette",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction & AdvancedResearch",
		DisplayPriority = 53,
		DisplayedName = "Bomber Corvette",
		Description = "<b>Type: Minelayer Corvette</b>\n<b>Description:</b>\n\nThe Bomber Corvette is an Oversized version of the Fighter Bomber. However, the Corvette version can drop explosive devices.\n\n<b>Requires:</b>\nCorvette Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_AssaultFrigate",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 60,
		DisplayedName = "Assault Frigate",
		Description = "<b>Type: Small Frigate</b>\n<b>Description:</b>\n\nMultipurpose attack frigate that uses two relatively weak weapon types to a great extent against Fighters and Corvettes.\n\n<b>Requires:</b>\nFrigate Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_TorpedoFrigate",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 65,
		DisplayedName = "Bomber Frigate",
		Description = "<b>Type: Small Frigate</b>\n<b>Description:</b>\n\nThe Bomber Frigate is yet another attempt to upscale of the bomber platform, able to make high speed runs at capital ships, unleashing it's weapons onto enemy hulls.\n\n<b>Requires:</b>\nFrigate Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_IonCannonFrigate",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 70,
		DisplayedName = "Plasma-Beam Frigate",
		Description = "<b>Type: Medium Frigate</b>\n<b>Description:</b>\n\nThe Firelance Plasma-Projector Frigate is nothing more than a Capital grade plasma projector with a frigate chassis wrapped around it. Very useful against capital ships.\n\n<b>Requires:</b>\nFrigate Production Facility\nTechnology II Module",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_MarineFrigate",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 75,
		DisplayedName = "$7052",
		Description = "<b>Type: Specialized Frigate</b>\n<b>Description:</b>\n\nThe Marine Frigate delivers highly-trained marines to board an enemy ship in the heat of battle and attept to take control of it.\n\n<b>Requires:</b>\nFrigate Production Facility\nTechnology II Module",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Carrier",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		Description = "<b>Type: Assault Carrier</b>\n<b>Description:</b>\n\nThe UNCG Carrier is the workhorse of the UNCG Fleet. Able to control and operate entire fleets over many sectors, or a simple resource operation. The current Mark VI design is over 60 years old, and counting.\n\n<b>Requires:</b>\nCapital Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_Crossbow_Cruiser",
		RequiredResearch = "LightCruisers",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 114,
		DisplayedName = "Assault Cruiser",
		Description = "<b>Type: Medium Cruiser</b>\n<b>Description:</b>\n\nThe Assault Cruiser is built for long range conflicts with Frigates, and does not perform well in the heat of Super-Capital Battles\n\n<b>Requires:</b>\nCapital Production Facility\nAssault Cruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Destroyer",
		RequiredResearch = "DestroyerTech",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 115,
		DisplayedName = "$7056",
		Description = "<b>Type: Destroyer</b>\n<b>Description:</b>\n\nThe UNCG Destroyer is used for heavy patrols on the UNCG/DSCG Borders. Originally, the design came from the old Solar System wars, and was refitted when the UNCG needed a Destroyer class vessel.\n\n<b>Requires:</b>\nCapital Production Facility\nDestroyer Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Battlecruiser",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 116,
		DisplayedName = "$7060",
		Description = "<b>Type: Battlecruiser</b>\n<b>Description:</b>\n\nThe Trafalgar is a refit heavy tanker used to transport goods through slipstream. With its Speed, armor, and weaponry, a lone trafalgar can take out an weakly defended planet.\n\n<b>Requires:</b>\nCapital Production Facility\nBattlecruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Battleship",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 121,
		DisplayedName = "Battleship",
		Description = "<b>Type: Heavy Battlecruiser</b>\n<b>Description:</b>\n\nThe Amaranth is aptly named, as the cruiser always prevails in any well played firefight. It is by far the most advanced ship built by either the UNCG or DSCG. The Amaranth is the only human ship with a full Tsaraii shield array and Tsaraii-Derived Slipstream Drive.\n\n<b>Requires:</b>\nCapital Production Facility\nBattlecruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Shipyard",
		RequiredResearch = "SCENABLED",
		RequiredShipSubSystems = "Hyperspace",
		DisplayPriority = 118,
		DisplayedName = "Factory",
		Description = "<b>Type: Factory</b>\n<b>Description:</b>\n\nThe Mobile Factory is literally a city-ship. It houses thousands of workers, crewman, and officers. It is the UNCG solution to the DSCG mobile construction platforms.\n\n<b>Requires:</b>\nSlipstream Module.",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_PulsarPlatform",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 142,
		DisplayedName = "Sniper Sentry",
		Description = "<b>Type: Mobile Platform</b>\n<b>Description:</b>\n\nThe Sniper Sentry is a great anti-Fighter/Corvette defense Platform. Originally designed for the Trafalgar, this platform can shoot down multiple squadrons before the enemy comes within firing distance.\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_GunTurret",
		RequiredResearch = "",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 141,
		DisplayedName = "Gatling Sentry",
		Description = "<b>Type: Mobile Platform</b>\n<b>Description:</b>\n\nThe Gatling Sentry shoots any Fighters and Corvettes that get through Sniper-Defense with 4500 Degree shells.\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_IonTurret",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 143,
		DisplayedName = "Ion Beam Sentry",
		Description = "<b>Type:Mobile Platform</b>\n<b>Description:</b>\n\nThe Ion Sentry sports two PPC-ION Turrets that can mow down Frigates and Destroyers at long range. Great at keeping Boarding Frigates out of the way.\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_platform_slipstream",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 144,
		DisplayedName = "Slipstream Platform",
		Description = "<b>Type:Mobile Platform</b>\n<b>Description:</b>\n\nThis Piece of engineering marvel allows ships (usually fighters) to make Slipstream jumps.\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ResourceCollector",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		Description = "<b>Type: Resource Collector</b>\n<b>Description:</b>\n\nBasic utility ship. Can gather Resources for conversion into Resource Units.\n\n<b>Requires:</b>\nNothing",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ResourceController",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		Description = "<b>Type: Mobile Resource Refinery</b>\n<b>Description:</b>\n\nThe Refinery serves as a mobile resource collection point that can dock up to 2 resource collectors at a time.\n\n<b>Requires:</b>\nNothing",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Probe",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 140,
		DisplayedName = "$7070",
		Description = "$7071",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ProximitySensor",
		RequiredResearch = "SensDisProbe",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7072",
		Description = "$7073",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ECMProbe",
		RequiredResearch = "ECMProbe",
		RequiredShipSubSystems = "",
		DisplayPriority = 160,
		DisplayedName = "$7074",
		Description = "$7075",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Shipyard_SPG",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		Description = "$7059",
	},
}
