-- LuaDC version 0.9.20
-- 9/9/2007 3:34:42 PM
-- LuaDC by Age2uN
-- on error send source file (compiled lua) and this outputfile to Age2uN@gmx.net
--
Ship = 0
SubSystem = 1
build = 
    { 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Production_Fighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "$7000", 
        Description = "$7001", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Production_Fighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "$7000", 
        Description = "$7001", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Production_Corvette", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 0, 
        DisplayedName = "$7002", 
        Description = "$7003", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Production_Corvette", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 0, 
        DisplayedName = "$7002", 
        Description = "$7003", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Production_Frigate", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 0, 
        DisplayedName = "$7004", 
        Description = "$7005", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Production_Frigate", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 0, 
        DisplayedName = "$7004", 
        Description = "$7005", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Production_CapShip", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "$7006", 
        Description = "$7007", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_SY_Production_CapShip", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "$7006", 
        Description = "$7007", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_PlatformControl", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "$7008", 
        Description = "$7009", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_PlatformControl", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 20, 
        DisplayedName = "$7008", 
        Description = "$7009", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_Research", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "$7010", 
        Description = "$7011", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_Research", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 0, 
        DisplayedName = "$7010", 
        Description = "$7011", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_ResearchAdvanced", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 10, 
        DisplayedName = "$7012", 
        Description = "$7013", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_ResearchAdvanced", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 10, 
        DisplayedName = "$7012", 
        Description = "$7013", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_Hyperspace", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 30, 
        DisplayedName = "$7014", 
        Description = "$7015", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_Hyperspace", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 30, 
        DisplayedName = "$7014", 
        Description = "$7015", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 40, 
        DisplayedName = "$7016", 
        Description = "$7017", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 40, 
        DisplayedName = "$7016", 
        Description = "$7017", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_CloakGenerator", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 50, 
        DisplayedName = "$7018", 
        Description = "$7019", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_CloakGenerator", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "Research", 
        DisplayPriority = 50, 
        DisplayedName = "$7018", 
        Description = "$7019", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Module_FireControl", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "AdvancedResearch", 
        DisplayPriority = 60, 
        DisplayedName = "$7020", 
        Description = "$7021", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Module_FireControl", 
        RequiredResearch = "", 
        RequiredFleetSubSystems = "AdvancedResearch", 
        DisplayPriority = 60, 
        DisplayedName = "$7020", 
        Description = "$7021", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Sensors_DetectHyperspace", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 150, 
        DisplayedName = "$7036", 
        Description = "$7037", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Sensors_DetectHyperspace", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 150, 
        DisplayedName = "$7036", 
        Description = "$7037", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Sensors_AdvancedArray", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 151, 
        DisplayedName = "$7022", 
        Description = "$7023", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Sensors_AdvancedArray", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 151, 
        DisplayedName = "$7022", 
        Description = "$7023", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_C_Sensors_DetectCloaked", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 152, 
        DisplayedName = "$7024", 
        Description = "$7025", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Sensors_DetectCloaked", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 152, 
        DisplayedName = "$7024", 
        Description = "$7025", }, 
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_platformcontrol",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 20,
        DisplayedName = "$7008",
        Description = "$7009", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_research",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 0,
        DisplayedName = "$7010",
        Description = "$7011", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_researchadvanced",
        RequiredResearch = "",
        RequiredFleetSubSystems = "Research",
        DisplayPriority = 10,
        DisplayedName = "$7012",
        Description = "$7013", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_hyperspace",
        RequiredResearch = "",
        RequiredFleetSubSystems = "Research",
        DisplayPriority = 30,
        DisplayedName = "$7014",
        Description = "$7015", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_hyperspaceinhibitor",
        RequiredResearch = "",
        RequiredFleetSubSystems = "Research",
        DisplayPriority = 40,
        DisplayedName = "$7016",
        Description = "$7017", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_firecontrol",
        RequiredResearch = "",
        RequiredFleetSubSystems = "AdvancedResearch",
        DisplayPriority = 60,
        DisplayedName = "$7020",
        Description = "$7021", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_sensors_detecthyperspace",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 150,
        DisplayedName = "$7036",
        Description = "$7037", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_sensors_advancedarray",
        RequiredResearch = "",
        RequiredShipSubSystems = "",
        DisplayPriority = 151,
        DisplayedName = "$7022",
        Description = "$7023", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_sensors_detectcloaked",
        RequiredResearch = "SensDisProbe",
        RequiredShipSubSystems = "",
        DisplayPriority = 152,
        DisplayedName = "$7024",
        Description = "$7025", },
    {
        Type = SubSystem,
        ThingToBuild = "hgn_BBC_module_cloakgenerator",
        RequiredResearch = "",
        RequiredFleetSubSystems = "Research",
        DisplayPriority = 50,
        DisplayedName = "$7018",
        Description = "$7019", },
    { 
        Type = Ship, 
        ThingToBuild = "Kpr_Mover", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 53, 
        DisplayedName = "$7913", 
        Description = "$7914", }, 
    { 
        Type = SubSystem, 
        ThingToBuild = "Hgn_MS_Production_CorvetteMover", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 10, 
        DisplayedName = "$7910", 
        Description = "$7911", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_Scout", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 10, 
        DisplayedName = "$7030", 
        Description = "<b>Type: Light Fighter</b>\n<b>Codename: Seeker</b>\n<b>Description:</b>\n\nThe Seeker Codename scout craft is a highly maneuverable strikcraft that can seek the location of enemys, or patrol the area. These ships have almost become obsolete, due to unmanned probes and active sensors.\n\n<b>Armed with:</b>\n1x Small Energy Gun\n1x Small EMP", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_Interceptor", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 20, 
        DisplayedName = "$7032", 
        Description = "<b>Type: Medium Fighter</b>\n<b>Codename: Interceptor</b>\n<b>Description:</b>\n\nThe Interceptor Codename Medium Fighter is the industry standard when it comes to dogfights. THis Fighter is build to take the extreme heat of capship combat, and the high speed turns of dogfights.\n\n<b>Armed with:</b>\n1x Plasma Driver, 1x Guided Plasma Torpedo", }, 
  { 
        Type = Ship, 
        ThingToBuild = "hgn_railgunfighter", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 32, 
        DisplayedName = "Rail Gun Fighter", 
        Description = "<b>Type: Medium Fighter</b>\n<b>Codename: Scorpion</b>\n<b>Description:</b>\n\nThe Scorpion Rail-Gun fighter is a Medium fighter that carriers a light rail gun. This ship is devistating to frigates, and can be to fighters.\n\n<b>Armed with:</b>\n1x Light Rail Gun", }, 
  { 
        Type = Ship, 
        ThingToBuild = "Hgn_AttackBomber", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 30, 
        DisplayedName = "$7034", 
        Description = "<b>Type: Medium Fighter</b>\n<b>Codename: Gettysburg</b>\n<b>Description:</b>\n\nThe Gettysburg bomber got its name from the codename of the project that was developing this bomber. A Solution was needed to take care of frigates while using very little resources, and time. This came arise to mounting to plasma tubes on the the side of a experimental strike fighter with an oversized powerplant.\n\n<b>Armed with:</b>\n2x Plasma Bomb Launchers", },  { 
        Type = Ship, 
        ThingToBuild = "hgn_lbomber", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FighterProduction", 
        DisplayPriority = 31, 
        DisplayedName = "Strategic Bomber", 
        Description = "<b>Type: Medium Fighter</b>\n<b>Codename: Phoenix</b>\n<b>Description:</b>\n\nThe Strategic Bomber was derived when two American Empire Industries decided to merge the plasma bomber technology with the interceptor, to come up with a fighter that could mop up frigates, as well as fighters.\n\n<b>Armed with:</b>\n1x Plasma Bomber Launcher\n1xPlasma Driver", }, 
    { 
        Type = Ship, 
        ThingToBuild = "hgn_superbomber", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 50, 
        DisplayedName = "Heavy Bomber", 
        Description = "<b>Type: Heavy Fighter</b>\n<b>Codename: Acolyte</b>\n<b>Description:</b>\n\nThe Acolyte is a massive bomber that uses twin powerplants to fire 4 capital grade plasma bomb launchers. This came about by merging two Gettysburg bombers and wrapping the ship around a corvette powerplant. This ship Codenameifies as a heavy fighter and/or Light Corvette.\n\n<b>Armed with:</b>\n4x Capital Plasma Drivers", }, 
 { 
        Type = Ship, 
        ThingToBuild = "Hgn_AssaultCorvette", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 51, 
        DisplayedName = "$7038", 
        Description = "<b>Type: Standard Corvette</b>\n<b>Codename: Bum-Rush</b>\n<b>Description:</b>\n\nThe Bum-Rush Standard Corvette Carriers a small number of armor-piercing Kinetic Shells. Reloading is done by using short-wave teleportation systems to transport shells, this is very expensive system to run.\n\n<b>Armed with:</b>\n2x Vulcan Turret", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_PulsarCorvette", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 52, 
        DisplayedName = "EMP Laser", 
        Description = "<b>Type: Standard Corvette</b>\n<b>Codename: Python</b>\n<b>Description:</b>\n\nThe Python is apptly named. The python was a snake on Earth that would coil around its victim and took the life out it. This Corvette is the same concept. It surrounds a vessel and fires a massive directed Emp Sniper into the side of the ship, pinning a ship while larger ships can pounce.\n\n<b>Armed with:</b>\n1x Small EMP Sniper", }, 
    { 
        Type = Ship, 
        ThingToBuild = "hgn_multiguncorvette", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CorvetteProduction", 
        DisplayPriority = 53, 
        DisplayedName = "Multi-Gun Corvette", 
        Description = "<b>Type: Standard Corvette</b>\n<b>Codename: Tracker</b>\n<b>Description:</b>\n\nThe Tracker\n\n<b>Armed with:</b>\n1x Small Energy Gun\n1x Small EMP", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_DefenseFieldFrigate", 
        RequiredResearch = "DefenseFieldFrigateShield", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 80, 
        DisplayedName = "$7044", 
        Description = "$7045", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_TorpedoFrigate", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 60, 
        DisplayedName = "Missile Frigate", 
        Description = "$7047", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_AssaultFrigate", 
        RequiredResearch = "InstaAdvancedFrigateTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 65, 
        DisplayedName = "Assault Frigate", 
        Description = "$7049", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_IonCannonFrigate", 
        RequiredResearch = "InstaAdvancedFrigateTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 70, 
        DisplayedName = "$7050", 
        Description = "$7051", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_MarineFrigate", 
        RequiredResearch = "InstaAdvancedFrigateTech", 
        RequiredShipSubSystems = "FrigateProduction", 
        DisplayPriority = 75, 
        DisplayedName = "$7052", 
        Description = "$7053", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_Carrier", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 110, 
        DisplayedName = "$7054", 
        Description = "$7055", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_Destroyer", 
        RequiredResearch = "DestroyerTech", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 116, 
        DisplayedName = "$7056", 
        Description = "$7057", }, 
   { 
        Type = Ship, 
        ThingToBuild = "Hgn_DestroyerHeavy", 
        RequiredResearch = "DestroyerTech", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 117, 
        DisplayedName = "Heavy Destroyer", 
        Description = "$7057", }, 
{ 
        Type = Ship, 
        ThingToBuild = "hgn_Sword_Cruiser", 
        RequiredResearch = "DestroyerTech", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 118, 
        DisplayedName = "Assault Cruiser", 
        Description = "$7057", }, 
{ 
        Type = Ship, 
        ThingToBuild = "hgn_Crossbow_Cruiser", 
        RequiredResearch = "DestroyerTech", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 119, 
        DisplayedName = "Ranged Cruiser", 
        Description = "$7057", }, 
 { 
        Type = Ship, 
        ThingToBuild = "Hgn_Battlecruiser", 
        RequiredResearch = "BattlecruiserIonWeapons", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 120, 
        DisplayedName = "$7060", 
        Description = "$7061", }, 
 { 
        Type = Ship, 
        ThingToBuild = "Hgn_Battleship", 
        RequiredResearch = "BattlecruiserIonWeapons", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 121, 
        DisplayedName = "Battleship", 
        Description = "$7061", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_PulsarPlatform", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "PlatformProduction", 
        DisplayPriority = 142, 
        DisplayedName = "Laser Sentry", 
        Description = "", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_GunTurret", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "PlatformProduction", 
        DisplayPriority = 141, 
        DisplayedName = "Gatling Sentry", 
        Description = "$7063", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_IonTurret", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "PlatformProduction", 
        DisplayPriority = 143, 
        DisplayedName = "Ion Beam Sentry", 
        Description = "$7065", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_ResourceCollector", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 120, 
        DisplayedName = "$7066", 
        Description = "$7067", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_ResourceController", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 130, 
        DisplayedName = "$7068", 
        Description = "$7069", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_Probe", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 140, 
        DisplayedName = "$7070", 
        Description = "$7071", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_ProximitySensor", 
        RequiredResearch = "SensDisProbe", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 150, 
        DisplayedName = "$7072", 
        Description = "$7073", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_ECMProbe", 
        RequiredResearch = "ECMProbe", 
        RequiredShipSubSystems = "", 
        DisplayPriority = 160, 
        DisplayedName = "$7074", 
        Description = "$7075", }, 
    { 
        Type = Ship, 
        ThingToBuild = "Hgn_Shipyard_SPG", 
        RequiredResearch = "", 
        RequiredShipSubSystems = "CapShipProduction", 
        DisplayPriority = 117, 
        DisplayedName = "$7058", 
        Description = "$7059", }, 
    }
