Ship = 0
SubSystem = 1

build =
{
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Production_Fighter",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		Description = "$7001",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_Fighter",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		Description = "$7001",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_bcfighter",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		Description = "$7001",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Production_Corvette",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		Description = "$7003",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_Corvette",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		Description = "$7003",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Production_Frigate",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		Description = "$7005",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_Frigate",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		Description = "$7005",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_production_frigate",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Hyperspace",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		Description = "$7005",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_CapShip",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		Description = "$7007",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_SY_Production_CapShip",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		Description = "$7007",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_sc_productioncapital",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		Description = "$7007",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_PlatformControl",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 10,
		DisplayedName = "$7008",
		Description = "$7009",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_PlatformControl",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 20,
		DisplayedName = "$7008",
		Description = "$7009",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		Description = "$7011",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		Description = "$7011",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_ResearchAdvanced",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		Description = "$7013",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_ResearchAdvanced",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		Description = "$7013",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_Hyperspace",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 30,
		DisplayedName = "Slipstream Generator",
		Description = "<b>Description:</b>  Slipstream Generators and Field Projectors. Allows nearby Frigates and Capital ships to hyperspace.  \n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b>Research Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_Hyperspace",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 30,
		DisplayedName = "Slipstream Generator",
		Description = "<b>Description:</b>  Slipstream Generators and Field Projectors allow nearby Frigates and Capital ships to hyperspace.\n\n<b>Type:</b> Module (Takes 1 Module Slot)\n\n<b>Prerequisites:</b>Research Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 40,
		DisplayedName = "$7016",
		Description = "$7017",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 40,
		DisplayedName = "$7016",
		Description = "$7017",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_CloakGenerator",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 50,
		DisplayedName = "Defence Field Generator",
		Description = "$7019",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_CloakGenerator",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 50,
		DisplayedName = "Defence Field Generator",
		Description = "$7019",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Module_FireControl",
		RequiredResearch = "",
		RequiredFleetSubSystems = "AdvancedResearch",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		Description = "$7021",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_SC_Smashercalibration",
		RequiredResearch = "",
		RequiredFleetSubSystems = "AdvancedResearch",
		DisplayPriority = 60,
		DisplayedName = "ICBM Launcher System",
		Description = "<b>Description:</b>  Devastating weapon system that can be launched at targets across vast distances and cause massive damage. The original version of this warhead was used to glass planets.\n\n<b>Type:</b> Module (Takes 1 Module Slot). \n\n<b>Prerequisites:</b>Advanced Research Module.",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Module_FireControl",
		RequiredResearch = "",
		RequiredFleetSubSystems = "AdvancedResearch",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		Description = "$7021",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Sensors_DetectHyperspace",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		Description = "$7037",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_SC_Sensors_DetectHyperspace",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		Description = "$7037",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Sensors_DetectHyperspace",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		Description = "$7037",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Sensors_AdvancedArray",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		Description = "$7023",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_SC_Sensors_AdvancedArray",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		Description = "$7023",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Sensors_AdvancedArray",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		Description = "$7023",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_C_Sensors_DetectCloaked",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		Description = "$7025",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_SC_Sensors_DetectCloaked",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		Description = "$7025",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Sensors_DetectCloaked",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		Description = "$7025",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_platformcontrol",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 20,
		DisplayedName = "$7008",
		Description = "$7009",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		Description = "$7011",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_researchadvanced",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		Description = "$7013",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_hyperspace",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		Description = "$7015",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_hyperspaceinhibitor",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 40,
		DisplayedName = "$7016",
		Description = "$7017",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_firecontrol",
		RequiredResearch = "",
		RequiredFleetSubSystems = "AdvancedResearch",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		Description = "$7021",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_sensors_detecthyperspace",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		Description = "$7037",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_sensors_advancedarray",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		Description = "$7023",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_sensors_detectcloaked",
		RequiredResearch = "SensDisProbe",
		RequiredShipSubSystems = "",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		Description = "$7025",
	},
	{
		Type = SubSystem,
		ThingToBuild = "hgn_BBC_module_cloakgenerator",
		RequiredResearch = "",
		RequiredFleetSubSystems = "Research",
		DisplayPriority = 50,
		DisplayedName = "Defence Field Generator",
		Description = "$7019",
	},
	{
		Type = Ship,
		ThingToBuild = "Kpr_Mover",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 53,
		DisplayedName = "$7913",
		Description = "$7914",
	},
	{
		Type = SubSystem,
		ThingToBuild = "Hgn_MS_Production_CorvetteMover",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 10,
		DisplayedName = "$7910",
		Description = "$7911",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Scout",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 10,
		DisplayedName = "$7030",
		Description = "<b>Type: Light Fighter</b>\n<b>Classname: Seeker</b>\n<b>Description:</b>\n\nThe Seeker scout craft is a highly maneuverable strikcraft that can seek the location of enemies, or patrol the area. These ships have almost become obsolete due to unmanned probes and active sensors.\n\n<b>Armed with:</b>\n1x Integrated Vulcan Turret\n1x Small Integrated EMP System (Once Upgraded)\n<b>Requires:</b>\nNothing",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Interceptor",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		DisplayPriority = 20,
		DisplayedName = "$7032",
		Description = "<b>Type: Medium Fighter</b>\n<b>Classname: Interceptor</b>\n<b>Description:</b>\n\nThe Interceptor Medium Fighter is the industry standard when it comes to dogfights. This -ighter is build to take the extreme heat of capship combat, and the high speed turns of dogfights.\n\n<b>Armed with:</b>\n1x Plasma Driver\n1x Guided Plasma Torpedo Launch Tube\n<b>Requires:</b>\nFighter Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_AttackBomber",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		DisplayPriority = 30,
		DisplayedName = "Attack Bomber",
		Description = "<b>Type: Medium Fighter</b>\n<b>Classname: Acolyte</b>\n<b>Description:</b>\n\nThe Acolyte bomber got its name after it's day-view battle after a prototype was accidentaly used in the now infamous battle in the Solar System wars in which much UNCG technology was derived. A solution was needed to take care of frigates while using very little resources, and time. This came arise to mounting to plasma tubes on the the side of a experimental strike fighter with an oversized powerplant.\n\n<b>Armed with:</b>\n2x Plasma Bomb Launchers (Fires Anti-Sub-System Bombs Once Upgraded)\n<b>Requires:</b>\nFighter Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_AssaultCorvette",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 51,
		DisplayedName = "Assault Corvette",
		Description = "<b>Type: Standard Corvette</b>\n<b>Classname: Bum-Rush</b>\n<b>Description:</b>\n\nThe Bum-Rush Standard Corvette carries a small number of armor-piercing Kinetic Shells. Reloading is done by using short-wave teleportation systems to transport shells, this is very expensive system to run.\n\n<b>Armed with:</b>\n1x Vulcan Turret\n1x FT-2 Minigun Turret\n<b>Requires:</b>\nCorvette Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_PulsarCorvette",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 52,
		DisplayedName = "Pulsar Corvette",
		Description = "<b>Type: Standard Corvette</b>\n<b>Classname: Python</b>\n<b>Description:</b>\n\nThe Python is aptly named. The python was a snake on Earth that would coil around its victim and take the life out it. This Corvette can fly around its target and fire a small laser into its side, devastating frigates.\n\n<b>Armed with:</b>\n1x Small Sniper Laser\n<b>Requires:</b>\nCorvette Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_railguncorvette",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		DisplayPriority = 53,
		DisplayedName = "Rail-Gun Corvette",
		Description = "<b>Type: Standard Corvette</b>\n<b>Classname: Sniper</b>\n<b>Description:</b>\n\nThe Sniper is a powerful Corvette that is armed with a scaled-down railgun to allow for much more damage than other corvettes.\n\n<b>Armed with:</b>\n1x Light Railgun\n<b>Requires:</b>\nCorvette Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_DefenseFieldFrigate",
		RequiredResearch = "DefenseFieldFrigateShield",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 80,
		DisplayedName = "$7044",
		Description = "<b>Type: Specialized Frigate</b>\n<b>Classname: Circumference</b>\n<b>Description:</b>\n\nThe Circumference class Defense Field Frigate is at the forefront UNCG technology. This frigate is capable of deploying a Energy Field around itself and other ships inside the sphere.\n\n<b>Armed with:</b>\n1x Weak Vulcan Cannon\n1x Defense Shield Projector\n<b>Requires:</b>\nDefense Field Research\nFrigate Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_TorpedoFrigate",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 65,
		DisplayedName = "Missile Frigate",
		Description = "<b>Type: Small Frigate</b>\n<b>Classname: Archer</b>\n<b>Description:</b>\n\nThe Archer class missile frigate uses 2 missile box's mounted on a small frigate chassis. A problem with using physical missiles is that they are in limited supply on the carrier, so before nano construction it was nowhere near possible. However, with research into ancient technology, the UNCG found that microslipstream conduits can be used to transport nanocells between the construction ship and the armed ship, making the missile frigate possible.\n\n<b>Armed with:</b>\n1x Vertical Heavy Missile Launcher\n2x Weak Vulcan Turrets\n<b>Requires:</b>\nFrigate Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_AssaultFrigate",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 60,
		DisplayedName = "Assault Frigate",
		Description = "<b>Type: Small Frigate</b>\n<b>Classname: Gladiator</b>\n<b>Description:</b>\n\nThe Gladiator is a multipurpose attack frigate that uses two relatively weak weaponry to a great extent against Fighters and Corvettes.\n\n<b>Armed With:</b>\n2x Small PPC\n2x Small Flak Cannon\n<b>Requires:</b>\nFrigate Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_IonCannonFrigate",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 70,
		DisplayedName = "$7050",
		Description = "<b>Type: Medium Frigate</b>\n<b>Classname: Firelance</b>\n<b>Description:</b>\n\nThe Firelance Plasma-Projector Frigate is nothing more than a Capital grade plasma projector with a frigate chassis wrapped around it. Very useful against capital ships.\n\n<b>Armed With:</b>\n1x Fixed Plasma Projector Cannon\n<b>Requires:</b>\nFrigate Production Facility\nAdvanced Research Module",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_MarineFrigate",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		DisplayPriority = 75,
		DisplayedName = "$7052",
		Description = "<b>Type: Specialized Frigate</b>\n<b>Classname: Seal</b>\n<b>Description:</b>\n\nThe Seal Marine Frigate delivers highly-trained marines to board a enemy ship in the heat of battle and attept to take it over.\n\n<b>Armed With:</b>\n1x Vulcan Turret\nMarine Boarding Party\n<b>Requires:</b>\nFrigate Production Facility\nAdvanced Research Module",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Carrier",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		Description = "<b>Type: Assault Carrier</b>\n<b>Classname: Whitecloud</b>\n<b>Description:</b>\n\nThe Whitecloud is based on an early design for a Transport tanker. When the UNCG needed small carriers to carry out tasks without using a full blown Super-Carrier, they enlisted this design and fitted it to suit as an Armored carrier, able to carry out any operation quickly, efficiently, and take the heat while doing it all.\n\n<b>Armed With:</b>\n2x Heavy 4x-Barrel DC Flak Turrets\n1x 4x4 Vertical Missile Launcher (Standard, Drone)\n2x FZ-99 Gatling Turrets\n<b>Requires:</b>\nCapital Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Destroyer",
		RequiredResearch = "DestroyerTech",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 116,
		DisplayedName = "$7056",
		Description = "<b>Type: Destroyer</b>\n<b>Classname: Resolute</b>\n<b>Description:</b>\n\nThe Resolute is the workhorse of small battles and outer partrol. Originally, the design came from the old Solar System wars, and was refitted when the UNCG needed a Destroyer class vessel.\n\n<b>Armed With:</b>\n1x 2x-Barrel Heavy Gatling Gun\n1x FZ-99 Gatling Turret\n2x 3-Coil Cannon\n<b>Requires:</b>\nCapital Production Facility\nDestroyer Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_heavydestroyer",
		RequiredResearch = "DestroyerTech",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 117,
		DisplayedName = "Heavy Destroyer",
		Description = "<b>Type: Heavy Destroyer</b>\n<b>Classname: Hannibal</b>\n<b>Description:</b>\n\nThe Hannibal is an upgraded version of the original resolute, and was intended to replace it, but it was too costly to do so, and so Hannibal has no Nuclear Arms capabilities.\n\n<b>Armed With:</b>\n1x Torpedo Bay\n1x 3-Coil Cannon\n1x 6x-Barrel Heavy Valencium Repeaters \n2x 4x-Barrel Heavy DC Flak Turrets\n1x 2x-Barrel Heavy Railgun\n1x FZ-99 Gatling Turret\n<b>Requires:</b>\nCapital Production Facility\nDestroyer Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_Sword_Cruiser",
		RequiredResearch = "LightCruisers",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 118,
		DisplayedName = "Assault Cruiser",
		Description = "<b>Type: Medium Cruiser</b>\n<b>Classname: Excalibur</b>\n<b>Description:</b>\n\nThe Excalibur is a Medium Cruiser designed to fight close range. Uses similar techniques to the Destroyers'.\n\n<b>Armed With:</b>\n1x 2x-Barrel Heavy Railgun Turrets\n1x 4x-Barrel Heavy DC Flak Turrets\n1x Missile Box\n10x 2x-Barrel Pulsar SCC Turrets\n<b>Requires:</b>\nCapital Production Facility\nLight Cruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_Crossbow_Cruiser",
		RequiredResearch = "LightCruisers",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 119,
		DisplayedName = "Ranged Cruiser",
		Description = "<b>Type: Medium Cruiser</b>\n<b>Classname: Crossbow</b>\n<b>Description:</b>\n\nThe Crossbow is a Medium Cruiser built for long range conflicts.\n\n<b>Armed With:</b>\n1x 2x-Barrel Particle Projector\n1x 3-Coil Cannon\n2x Heavy Gatling Gun\n1x 6x-Barrel Plasma Battery\n1x 2x-Barrel Heavy Railguns\n2x Missile Boxes\n<b>Requires:</b>\nCapital Production Facility\nLight Cruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Shipyard",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		Description = "$7059",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Superfortress",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		DisplayPriority = 120,
		DisplayedName = "Super Fortress",
		Description = "$7059",
	},
	{
		Type = Ship,
		ThingToBuild = "hgn_heavybattlecruiser",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 122,
		DisplayedName = "Heavy Cruiser",
		Description = "<b>Type: Heavy Cruiser</b>\n<b>Classname: Ironclad</b>\n<b>Description:</b>\n\nThis cruiser is truly powerful in most any situation, it is an invaluable asset.\n\n<b>Armed With:</b>\n2x Heavy Railgun\n2x Heavy Gatling Gun\n2x 6x-Barrel Plasma Pulse\n1x Missile Box\n1x PPC Turret\n2x Nuclear Missile Bays\n2x Flak Cannons\n<b>Requires:</b>\nCapital Production Facility\nBattlecruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Battlecruiser",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 121,
		DisplayedName = "$7060",
		Description = "<b>Type: Heavy Battlecruiser</b>\n<b>Classname: Trafalgar</b>\n<b>Description:</b>\n\nThe Trafalgar is a massive cruiser built to instill terror in its enemies. With its Speed, armor, and weaponry, a lone trafalgar can take out an weakly defended planet.\n\n<b>Armed With:</b>\n2x Heavy Railgun Turrets\n2x FZ-99 Gatling Turrets\n2x 6x-Barrel Plasma Batteries\n3x Torpedo Launcher Bays\n3x PPC Turrets\n4x Heavy Flak Turrets\n4x 4x-Barrel DC Turrets\n2x Missile Boxes\n1x 2x-Barrel Particle Projectors\n<b>Requires:</b>\nCapital Production Facility\nBattlecruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Battleship",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 123,
		DisplayedName = "Battleship",
		Description = "<b>Type: Super-Heavy Cruiser</b>\n<b>Classname: Valencia</b>\n<b>Description:</b>\n\nThe Valencia is nothing more than a scaled up Trafalgar Chassis, with more weaponry, larger reactors, and heavier armor. It was designed to smash any and ALL resistance in its path. Its brilliant commanders, UNCG Elite Guards, and its armament allows a cruiser of this magnitude to be able to smash an entire defended world into bits.\n\n<b>Armed With:</b>\n2x Heavy Railgun Turrets\n2x FZ-99 Gatling Turrets\n2x 6x-Barrel Plasma Batteries\n2x Missile Boxes\n1x 2x-Barrel Particle Projector\n<b>Requires:</b>\nCapital Production Facility\nBattlecruiser Chassis Research",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_PulsarPlatform",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 142,
		DisplayedName = "Sniper Sentry",
		Description = "<b>Type: Mobile Platform</b>\n<b>Description:</b>\n\nThe Sniper Sentry is a great anti-Fighter/Corvette defense Platform. Originally designed for the Trafalgar, this platform can shoot down multiple squadrons before the enemy comes within firing distance.\n\n<b>Armed with:</b>\n2x Sniper Lasers\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_GunTurret",
		RequiredResearch = "",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 141,
		DisplayedName = "Gatling Sentry",
		Description = "<b>Type: Mobile Platform</b>\n<b>Description:</b>\n\nThe Gatling Sentry shoots any Fighters and Corvettes that get through Sniper-Defense with 4500 Degree shells.\n\n<b>Armed with:</b>\n2x FT-01 Gatling Turrets\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_IonTurret",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		DisplayPriority = 143,
		DisplayedName = "Ion Beam Sentry",
		Description = "<b>Type:Mobile Platform</b>\n<b>Description:</b>\n\nThe Ion Sentry sports two PPC-ION Turrets that can mow down Frigates and Destroyers at long range. Great at keeping Boarding Frigates out of the way.\n\n<b>Armed with:</b>\n2x PPC-ION Turrets\n\n<b>Requires:</b>\nPlatform Production Facility",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ResourceCollector",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		Description = "<b>Type: Resource Collector</b>\n<b>Description:</b>\n\nBasic utility ship. Can gather Resources for conversion into Resource Units.\n\n<b>Armed with:</b>\nRepair Tools (Once Upgraded)<b>Requires:</b>\nNothing",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ResourceController",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 130,
		DisplayedName = "UNCG Resource Collector",
		Description = "<b>Type: Mobile Resource Refinery</b>\n<b>Codename: Pacer</b>\n\n<b>Description:</b>\n\nThe Pacer serves as a mobile resource collection point that can dock up to 2 resource collectors at a time.\n\n<b>Armed with:</b>\n4x Vulcan Turret\n1x FT-2 Minigun Turret\n<b>Requires:</b>\nNothing",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Probe",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		DisplayPriority = 140,
		DisplayedName = "$7070",
		Description = "$7071",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ProximitySensor",
		RequiredResearch = "SensDisProbe",
		RequiredShipSubSystems = "",
		DisplayPriority = 150,
		DisplayedName = "$7072",
		Description = "$7073",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_ECMProbe",
		RequiredResearch = "ECMProbe",
		RequiredShipSubSystems = "",
		DisplayPriority = 160,
		DisplayedName = "$7074",
		Description = "$7075",
	},
	{
		Type = Ship,
		ThingToBuild = "Hgn_Shipyard_SPG",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		Description = "$7059",
	},
}
