Icon_Speed = "data:ui/newui/research/icons/speed.mres"
Icon_Health = "data:ui/newui/research/icons/health.mres"
Icon_Tech = "data:ui/newui/research/icons/tech.mres"
Icon_Ability = "data:ui/newui/research/icons/ability.mres"
Icon_Build = "data:ui/newui/research/icons/build.mres"
Modifier = 0
Ability = 1
AllShips = 0
Family = 1
Ship = 2

research =
{
	{
		Name = "InstaAdvancedFrigateTech",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch",
		Cost = 0,
		Time = 0,
		DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
		DisplayPriority = 1,
		Description = "",
		TargetName = "Hgn_Shipyard",
	},
	{
		Name = "GraviticAttractionMines",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7500",
		DisplayPriority = 2,
		Description = "$7501",
		TargetName = "Hgn_MinelayerCorvette",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7200",
	},
	{
		Name = "PlatformIonWeapons",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7502",
		DisplayPriority = 24,
		Description = "$7503",
		TargetName = "Hgn_IonTurret",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7201",
	},
	{
		Name = "DestroyerTech",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7507",
		DisplayPriority = 3,
		Description = "$7508",
		TargetName = "Hgn_Destroyer",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7203",
	},
	{
		Name = "LightCruisers",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "Light Cruisers",
		DisplayPriority = 2,
		Description = "The Light Cruisers are two of the best suited ships ever made. The Ranged cruiser sports Weapons that can pick off enemys from afar, and the Assault (CQB) Cruiser sports 5 parallel cannons that pick off enemys like a pirate vessel.",
		TargetName = "hgn_Crossbow_Cruiser",
		Icon = Icon_Tech,
		ShortDisplayedName = "Light Cruisers",
	},
	{
		Name = "BattlecruiserIonWeapons",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7504",
		DisplayPriority = 1,
		Description = "$7505",
		TargetName = "Hgn_BattleCruiser",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7202",
	},
	{
		Name = "ECMProbe",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7509",
		DisplayPriority = 4,
		Description = "$7510",
		TargetName = "Hgn_ECMProbe",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7204",
	},
	{
		Name = "SensDisProbe",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7650",
		DisplayPriority = 5,
		Description = "$7651",
		TargetName = "Hgn_ProximitySensor",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7214",
	},
	{
		Name = "DamageMoverTech",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 500,
		Time = 60,
		DisplayedName = "$7900",
		DisplayPriority = 29,
		Description = "$7901",
		TargetName = "Hgn_Shipyard",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7902",
	},
	{
		Name = "RadiationDefenseField",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 500,
		Time = 60,
		DisplayedName = "$7905",
		DisplayPriority = 30,
		Description = "$7906",
		UpgradeType = Ability,
		TargetType = Ship,
		UpgradeName = "DefenseFieldShield",
		TargetName = "Hgn_DefenseFieldFrigate",
		Icon = Icon_Tech,
		ShortDisplayedName = "$7907",
	},
	{
		Name = "ImprovedTorpedo",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7515",
		DisplayPriority = 29,
		Description = "$7516",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7207",
	},
	{
		Name = "AttackBomberImprovedBombs",
		RequiredResearch = "",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7517",
		DisplayPriority = 30,
		Description = "$7518",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "MaxHealth",
		UpgradeValue = 1.0,
		Icon = Icon_Ability,
		ShortDisplayedName = "$7208",
	},
	{
		Name = "ScoutEMPAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7519",
		DisplayPriority = 1,
		Description = "$7520",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_Scout",
		UpgradeName = "SpecialAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7209",
	},
	{
		Name = "DefenseFieldFrigateShield",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7521",
		DisplayPriority = 32,
		Description = "$7522",
		TargetName = "Hgn_DefenseFieldFrigate",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7210",
	},
	--Drone Upgrades
	{
		Name = "DroneMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 150,
		Time = 30,
		DisplayedName = "+5% Drone Speed",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Drone conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Drone",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.05,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	
	{
		Name = "DroneHealthUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 150,
		Time = 45,
		DisplayedName = "+10% Drone Health",
		DisplayPriority = 82,
		Description = "<b>Description:</b> Improves Drone Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Drone",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	
	{
		Name = "DroneWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 250,
		Time = 40,
		DisplayedName = "+5% DroneWeapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Drone Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Drone",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "DroneWeaponUpgradePartTwo",
		RequiredResearch = "DroneWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Drone",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Interceptor Upgrades
	{
		Name = "InterceptorMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 300,
		Time = 30,
		DisplayedName = "+5% Interceptor Speed",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Interceptor conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Interceptor",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.05,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "InterceptorMAXSPEEDUpgrade2",
		RequiredResearch = "InterceptorMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & FighterProduction",
		Cost = 500,
		Time = 40,
		DisplayedName = "+5% Interceptor Speed II",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Interceptor conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Interceptor",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed II",
	},
	
	{
		Name = "InterceptorHealthUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 200,
		Time = 60,
		DisplayedName = "+10% Interceptor Health",
		DisplayPriority = 82,
		Description = "<b>Description:</b> Improves Inteceptor Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Interceptor",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	
	{
		Name = "InterceptorWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+10% Interceptor Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Interceptor Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Interceptor",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Weapons",
	},
	{
		Name = "InterceptorWeaponUpgradePartTwo",
		RequiredResearch = "InterceptorWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Interceptor",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	
	{
		Name = "InterceptorUseAfterburner",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 550,
		Time = 30,
		DisplayedName = "Interceptor Afterburner",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Interceptor to use Afterburners in attack maneuvers. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_Interceptor",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "Afterburner",
	},
	--Attack Bomber Upgrades
	{
		Name = "AttackBomberMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 350,
		Time = 45,
		DisplayedName = "+5% Attack Bomber Speed",
		DisplayPriority = 87,
		Description = "<b>Description:</b> Improves Attack Bomber conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.05,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "AttackBomberMAXSPEEDUpgrade2",
		RequiredResearch = "AttackBomberMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & FighterProduction",
		Cost = 450,
		Time = 55,
		DisplayedName = "+5% Attack Bomber Speed II",
		DisplayPriority = 87,
		Description = "<b>Description:</b> Improves Attack Bomber conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed II",
	},
	
	{
		Name = "AttackBomberHealthUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 200,
		Time = 60,
		DisplayedName = "+8% Attack Bomber Health",
		DisplayPriority = 82,
		Description = "<b>Description:</b> Improves Attack Bomber Hulls by 8%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.08,
		Icon = Icon_Health,
		ShortDisplayedName = "+8% Health",
	},
	
	{
		Name = "AttackBomberWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Attack Bomber Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Attack Bomber Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "AttackBomberWeaponUpgradePartTwo",
		RequiredResearch = "AttackBomberWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	
	{
		Name = "AttackBomberUseEMPBombs",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		Cost = 550,
		Time = 30,
		DisplayedName = "Attack Bomber EMP Bombs",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Attack Bomber to use EMP Bombs in attacks. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomber",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "EMP Bombs",
	},

	--Assault Corvette
	{
		Name = "AssaultCorvetteHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 500,
		Time = 40,
		DisplayedName = "+15% Assault Corvette Health",
		DisplayPriority = 200,
		Description = "<b>Description:</b> Improves Assualt Corvette Hulls by 15%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+15% Health",
	},
	{
		Name = "AssaultCorvetteHealthUpgrade2",
		RequiredResearch = "AssaultCorvetteHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 750,
		Time = 50,
		DisplayedName = "+5% Assault Corvette Health",
		DisplayPriority = 200,
		Description = "<b>Description:</b> Improves Assualt Corvette Hulls by an additional 5%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.20,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	
	{
		Name = "AssaultCorvetteMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 300,
		Time = 40,
		DisplayedName = "+15% Assaullt Corvette Speed",
		DisplayPriority = 203,
		Description = "<b>Description:</b> Improves Assault Corvette conventional drive systems by 15%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.15,
		Icon = Icon_Speed,
		ShortDisplayedName = "+15% MaxSpeed",
	},
	{
		Name = "AssaultCorvetteMAXSPEEDUpgrade2",
		RequiredResearch = "AssaultCorvetteMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 500,
		Time = 50,
		DisplayedName = "+10% Assault Corvette Speed",
		DisplayPriority = 203,
		Description = "<b>Description:</b> Improves Assault Corvette conventional drive systems by and additional 10%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	
	{
		Name = "AssaultCorvetteWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Assault Corvette Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Assault Corvette Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvette",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "AssaultCorvetteWeaponUpgradePartTwo",
		RequiredResearch = "AssaultCorvetteWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvette",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	
	--Pulsar Corvette Upgrades
	{
		Name = "PulsarCorvetteHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 400,
		Time = 40,
		DisplayedName = "+8% Pulsar Corvette Health",
		DisplayPriority = 206,
		Description = "<b>Description:</b> Improves Pulsar Corvette Hulls by 8%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.08,
		Icon = Icon_Health,
		ShortDisplayedName = "+8% Health",
	},
	{
		Name = "PulsarCorvetteHealthUpgrade2",
		RequiredResearch = "PulsarCorvetteHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 750,
		Time = 50,
		DisplayedName = "+12% Pulsar Corvette Health",
		DisplayPriority = 206,
		Description = "<b>Description:</b> Improves Pulsar Corvette Hulls by and additional 12%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.2,
		Icon = Icon_Health,
		ShortDisplayedName = "+12% Health",
	},
	
	{
		Name = "PulsarCorvetteMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 300,
		Time = 40,
		DisplayedName = "+7% Pulsar Corvette Speed",
		DisplayPriority = 209,
		Description = "<b>Description:</b> Improves Pulsar Corvette conventional drive systems by 7%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.07,
		Icon = Icon_Speed,
		ShortDisplayedName = "+7% MaxSpeed",
	},
	{
		Name = "PulsarCorvetteMAXSPEEDUpgrade2",
		RequiredResearch = "PulsarCorvetteMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 750,
		Time = 50,
		DisplayedName = "+3% Pulsar Corvette Speed",
		DisplayPriority = 209,
		Description = "<b>Description:</b> Improves Pulsar Corvette conventional drive systems by an additional 3%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.1,
		Icon = Icon_Speed,
		ShortDisplayedName = "+3% MaxSpeed",
	},
	
	{
		Name = "PulsarCorvetteWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Pulsar Corvette Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Pulsar Corvette Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "PulsarCorvetteWeaponUpgradePartTwo",
		RequiredResearch = "PulsarCorvetteWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	
	{
		Name = "PulsarCorvetteUseIonCannon",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 750,
		Time = 40,
		DisplayedName = "Pulsar Corvette Plasma Beam",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Pulsar Corvette to use Plasma Beams in attacks. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_PulsarCorvette",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "Plasma Beam",
	},
	--Bomber Corvette Upgrades
	{
		Name = "BomberCorvetteHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 400,
		Time = 40,
		DisplayedName = "+12% BomberCorvette Health",
		DisplayPriority = 206,
		Description = "<b>Description:</b> Improves Bomber Hulls by 12%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_minelayercorvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.12,
		Icon = Icon_Health,
		ShortDisplayedName = "+12% Health",
	},
	{
		Name = "BomberCorvetteHealthUpgrade2",
		RequiredResearch = "BomberCorvetteHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 750,
		Time = 50,
		DisplayedName = "+8% Bomber Corvette Health",
		DisplayPriority = 206,
		Description = "<b>Description:</b> Improves Bomber Corvette Hulls by and additional 12%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_minelayercorvette",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.2,
		Icon = Icon_Health,
		ShortDisplayedName = "+8% Health",
	},
	
	{
		Name = "BomberCorvetteMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 300,
		Time = 40,
		DisplayedName = "+7% Bomber Corvette Speed",
		DisplayPriority = 209,
		Description = "<b>Description:</b> Improves Bomber Corvette conventional drive systems by 7%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_minelayercorvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.07,
		Icon = Icon_Speed,
		ShortDisplayedName = "+7% MaxSpeed",
	},
	{
		Name = "BomberCorvetteMAXSPEEDUpgrade2",
		RequiredResearch = "BomberCorvetteMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		Cost = 750,
		Time = 50,
		DisplayedName = "+3% Bomber Corvette Speed",
		DisplayPriority = 209,
		Description = "<b>Description:</b> Improves Bomber Corvette conventional drive systems by an additional 3%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_minelayercorvette",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.1,
		Icon = Icon_Speed,
		ShortDisplayedName = "+3% MaxSpeed",
	},
	
	{
		Name = "BomberCorvetteWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Bomber Corvette Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Bomber Corvette Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_minelayercorvette",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "BomberCorvetteWeaponUpgradePartTwo",
		RequiredResearch = "BomberCorvetteWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_minelayercorvette",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Torpedo Frigate Upgrades
	{
		Name = "TorpedoFrigateHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 800,
		Time = 60,
		DisplayedName = "+15% Bomber Frigate Health",
		DisplayPriority = 300,
		Description = "<b>Description:</b> Improves Bomber Frigate Hulls by 15%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+15% Health",
	},
	{
		Name = "TorpedoFrigateHealthUpgrade2",
		RequiredResearch = "TorpedoFrigateHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 1400,
		Time = 75,
		DisplayedName = "+10% Bomber Frigate Health",
		DisplayPriority = 300,
		Description = "<b>Description:</b> Improves Bomber Frigate Hulls by an additional 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.25,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "TorpedoFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 500,
		Time = 50,
		DisplayedName = "+20% Bomber Frigate Speed",
		DisplayPriority = 303,
		Description = "<b>Description:</b> Improves Bomber Frigate conventional drive systems by 20%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "+20% MaxSpeed",
	},
	{
		Name = "TorpedoFrigateMAXSPEEDUpgrade2",
		RequiredResearch = "TorpedoFrigateMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 750,
		Time = 70,
		DisplayedName = "+5% Bomber Frigate Speed",
		DisplayPriority = 303,
		Description = "<b>Description:</b> Improves Bomber Frigate conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.25,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "TorpedoFrigateWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+8% Bomber Frigate Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Bomber Frigate Weapon systems by 8%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "+8% Weapons",
	},
	{
		Name = "TorpedoFrigateWeaponUpgradePartTwo",
		RequiredResearch = "TorpedoFrigateWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_TorpedoFrigate",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Ion Cannon Frigate Upgrades
	{
		Name = "IonCannonFrigateHealthUpgrade1",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 800,
		Time = 60,
		DisplayedName = "+18% Plasma-Beam Frigate Health",
		DisplayPriority = 306,
		Description = "<b>Description:</b> Improves Plasma-Beam Frigate Hulls by 18%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonCannonFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.18,
		Icon = Icon_Health,
		ShortDisplayedName = "+18% Health",
	},
	{
		Name = "IonCannonFrigateHealthUpgrade2",
		RequiredResearch = "IonCannonFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 1400,
		Time = 75,
		DisplayedName = "+12% Plasma-Beam Frigate Health",
		DisplayPriority = 306,
		Description = "<b>Description:</b> Improves Bomber Frigate Hulls by an additional 12%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonCannonFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.30,
		Icon = Icon_Health,
		ShortDisplayedName = "+12% Health",
	},
	{
		Name = "IonCannonFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 500,
		Time = 50,
		DisplayedName = "+4% Plasma-Beam Frigate Speed",
		DisplayPriority = 309,
		Description = "<b>Description:</b> Improves Plasma-Beam Frigate conventional drive systems by 4%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonCannonFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.04,
		Icon = Icon_Speed,
		ShortDisplayedName = "+4% MaxSpeed",
	},
	{
		Name = "IonCannonFrigateMAXSPEEDUpgrade2",
		RequiredResearch = "IonCannonFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 750,
		Time = 70,
		DisplayedName = "+6% Plasma-Beam Frigate Speed",
		DisplayPriority = 309,
		Description = "<b>Description:</b> Improves Bomber Frigate conventional drive systems by and additional 6%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonCannonFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+6% Health",
	},
	{
		Name = "IonCannonFrigateWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+14% Plasma-Beam Frigate Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Bomber Frigate Weapon systems by 14%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonCannonFrigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "+14% Weapons",
	},
	{
		Name = "IonCannonFrigateWeaponUpgradePartTwo",
		RequiredResearch = "IonCannonFrigateWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonCannonFrigate",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.14,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Assault Frigate Upgrades
	{
		Name = "AssaultFrigateHealthUpgrade1",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 800,
		Time = 60,
		DisplayedName = "+7% Assault Frigate Health",
		DisplayPriority = 312,
		Description = "<b>Description:</b> Improves Assault Frigate Hulls by 7%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.07,
		Icon = Icon_Health,
		ShortDisplayedName = "+7% Health",
	},
	{
		Name = "AssaultFrigateHealthUpgrade2",
		RequiredResearch = "AssaultFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 1400,
		Time = 75,
		DisplayedName = "+4% Assault Frigate Health",
		DisplayPriority = 312,
		Description = "<b>Description:</b> Improves Assault Frigate Hulls by an additional 4%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.11,
		Icon = Icon_Health,
		ShortDisplayedName = "+4% Health",
	},
	{
		Name = "AssaultFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 500,
		Time = 50,
		DisplayedName = "+11% Assault Frigate Speed",
		DisplayPriority = 315,
		Description = "<b>Description:</b> Improves Assault Frigate conventional drive systems by 11%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.11,
		Icon = Icon_Speed,
		ShortDisplayedName = "+11% MaxSpeed",
	},
	{
		Name = "AssaultFrigateMAXSPEEDUpgrade2",
		RequiredResearch = "AssaultFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 750,
		Time = 70,
		DisplayedName = "+5% Assault Frigate Speed",
		DisplayPriority = 315,
		Description = "<b>Description:</b> Improves Assault Frigate conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.16,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "AssaultFrigateWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+12% Assault Frigate Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Assault Frigate Weapon systems by 12%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultFrigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.12,
		Icon = Icon_Tech,
		ShortDisplayedName = "+12% Weapons",
	},
	{
		Name = "AssaultFrigateWeaponUpgradePartTwo",
		RequiredResearch = "AssaultFrigateWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultFrigate",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.12,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Marine Frigate Upgrades 
	{
		Name = "MarineFrigateHealthUpgrade1",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 800,
		Time = 60,
		DisplayedName = "+7% Marine Frigate Health",
		DisplayPriority = 312,
		Description = "<b>Description:</b> Improves Marine Frigate Hulls by 7%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MarineFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.07,
		Icon = Icon_Health,
		ShortDisplayedName = "+7% Health",
	},
	{
		Name = "MarineFrigateHealthUpgrade2",
		RequiredResearch = "MarineFrigateHealthUpgrade1 & InstaAdvancedFrigateTech",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 1400,
		Time = 75,
		DisplayedName = "+4% Marine Frigate Health",
		DisplayPriority = 312,
		Description = "<b>Description:</b> Improves Marine Frigate Hulls by an additional 4%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MarineFrigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.11,
		Icon = Icon_Health,
		ShortDisplayedName = "+4% Health",
	},
	{
		Name = "MarineFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		Cost = 500,
		Time = 50,
		DisplayedName = "+11% Marine Frigate Speed",
		DisplayPriority = 315,
		Description = "<b>Description:</b> Improves Marine Frigate conventional drive systems by 11%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MarineFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.11,
		Icon = Icon_Speed,
		ShortDisplayedName = "+11% MaxSpeed",
	},
	{
		Name = "MarineFrigateMAXSPEEDUpgrade2",
		RequiredResearch = "MarineFrigateMAXSPEEDUpgrade1 & InstaAdvancedFrigateTech",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		Cost = 750,
		Time = 70,
		DisplayedName = "+5% Marine Frigate Speed",
		DisplayPriority = 315,
		Description = "<b>Description:</b> Improves Marine Frigate conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Frigate Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MarineFrigate",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.16,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "MarineFrigateWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+12% Marine Frigate Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Marine Frigate Weapon systems by 12%. \n\n<b>Prerequisites:</b> Technology I Module and Corvette Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MarineFrigate",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.12,
		Icon = Icon_Tech,
		ShortDisplayedName = "+12% Weapons",
	},
	{
		Name = "MarineFrigateWeaponUpgradePartTwo",
		RequiredResearch = "MarineFrigateWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MarineFrigate",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.12,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Carrier Upgrades
	{
		Name = "CarrierHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 750,
		Time = 40,
		DisplayedName = "+30% Carrier Health",
		DisplayPriority = 61,
		Description = "<b>Description:</b> Improves Carrier Hulls by 30%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.3,
		Icon = Icon_Health,
		ShortDisplayedName = "+30% Health",
	},
	{
		Name = "CarrierHealthUpgrade2",
		RequiredResearch = "CarrierHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 900,
		Time = 60,
		DisplayedName = "+10% Carrier Health",
		DisplayPriority = 61,
		Description = "<b>Description:</b> Improves Carrier Hulls an additional 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.4,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "CarrierHealthUpgrade3",
		RequiredResearch = "CarrierHealthUpgrade2",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 1100,
		Time = 60,
		Description = "<b>Description:</b> Improves Carrier Hulls an additional 5%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		DisplayPriority = 61,
		Description = "+5% Carrier Health",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.45,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Carrier",
	},
	
	{
		Name = "CarrierMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 500,
		Time = 30,
		DisplayedName = "+10% Carrier Speed",
		DisplayPriority = 64,
		Description = "<b>Description:</b> Improves Carrier conventional drive systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.1,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	{
		Name = "CarrierMAXSPEEDUpgrade2",
		RequiredResearch = "CarrierMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 750,
		Time = 40,
		DisplayedName = "+5 Carrier Speed",
		DisplayPriority = 64,
		Description = "<b>Description:</b> Improves Carrier conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.15,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	
	{
		Name = "CarrierBUILDSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 1500,
		Time = 60,
		DisplayedName = "-30% Carrier Build Time",
		DisplayPriority = 65,
		Description = "<b>Description:</b> Allows Carrer to Build ships 30% Faster. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.3,
		Icon = Icon_Build,
		ShortDisplayedName = "-30% Build Time",
	},
	
	{
		Name = "CarrierWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 2000,
		Time = 100,
		DisplayedName = "+10% Carrier Defense",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Carrier Defense systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Defense",
	},
	{
		Name = "CarrierWeaponUpgradePartTwo",
		RequiredResearch = "CarrierWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "+10% Battleship Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Carrier Defense systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Weapons",
	},
	
	{
		Name = "CarrierUseNukes",
		RequiredResearch = "CarrierWeaponUpgrade",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 550,
		Time = 30,
		DisplayedName = "Carrier Nuclear Weapons",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Carrier to use Nuclear weapons in defense. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_Carrier",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "Nuclear Weapons",
	},
		--Battlecruiser Upgrades
	{
		Name = "BattlecruiserHealthUpgrade1",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 45,
		DisplayedName = "+12% Battlecruiser Health",
		DisplayPriority = 401,
		Description = "<b>Description:</b> Improves Battlecruiser Hulls by 12%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_BattleCruiser",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.12,
		Icon = Icon_Health,
		ShortDisplayedName = "+12% MaxHealth",
	},
	{
		Name = "BattlecruiserHealthUpgrade2",
		RequiredResearch = "BattlecruiserHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 1500,
		Time = 75,
		DisplayedName = "+8% Battlecruiser Health",
		DisplayPriority = 401,
		Description = "<b>Description:</b> Improves Battlecruiser Hulls by an additional 8%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_BattleCruiser",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.2,
		Icon = Icon_Health,
		ShortDisplayedName = "+8% MaxHealth",
	},
	
	{
		Name = "BattlecruiserMAXSPEEDUpgrade1",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 30,
		DisplayedName = "+20% Battlecruiser Speed",
		DisplayPriority = 403,
		Description = "<b>Description:</b> Improves Battlecruiser speed by 20%, allowing them to move faster. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battlecruiser",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "+20% MaxSpeed",
	},
	
	{
		Name = "BattlecruiserWeaponUpgrade",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 3000,
		Time = 100,
		DisplayedName = "+5% Battlecruiser Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Battlecruiser Weapon systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battlecruiser",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
	{
		Name = "BattlecruiseWeaponUpgradePartTwo",
		RequiredResearch = "BattleshipWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "+10% Battleship Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Battleship Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battlecruiser",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Weapons",
	},
		--Battleship Upgrades
	{
		Name = "BattleshipHealthUpgrade1",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 2000,
		Time = 60,
		DisplayedName = "+10% Battleship Health",
		DisplayPriority = 402,
		Description = "<b>Description:</b> Improves Battleship Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "BattleshipHealthUpgrade2",
		RequiredResearch = "BattleshipHealthUpgrade1",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 2150,
		Time = 75,
		DisplayedName = "+10% Battleship Health II",
		DisplayPriority = 402,
		Description = "<b>Description:</b> Improves Battleship Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.2,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health II",
	},
	{
		Name = "BattleshipHealthUpgrade3",
		RequiredResearch = "BattleshipHealthUpgrade2",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 2300,
		Time = 100,
		DisplayedName = "+20% Battleship Health",
		DisplayPriority = 402,
		Description = "<b>Description:</b> Improves Battleship Hulls by 20%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.4,
		Icon = Icon_Health,
		ShortDisplayedName = "+20% Health",
	},
	
	{
		Name = "BattleshipMAXSPEEDUpgrade1",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 30,
		DisplayedName = "+5% Battleship Speed",
		DisplayPriority = 404,
		Description = "<b>Description:</b> Improves Battleship conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.05,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "BattleshipMAXSPEEDUpgrade2",
		RequiredResearch = "BattleshipMAXSPEEDUpgrade1",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1500,
		Time = 30,
		DisplayedName = "+10% Battleship Speed",
		DisplayPriority = 404,
		Description = "<b>Description:</b> Improves Battleship conventional drive systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.15,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	
	{
		Name = "BattleshipWeaponUpgrade",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 3000,
		Time = 100,
		DisplayedName = "+10% Battleship Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Battleship Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Weapons",
	},
	{
		Name = "BattleshipWeaponUpgradePartTwo",
		RequiredResearch = "BattleshipWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "+10% Battleship Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Battleship Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Weapons",
	},
	
	{
		Name = "BattleshipUseRepulsor",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 550,
		Time = 30,
		DisplayedName = "Battleship Repulsor",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Battleship to use Repulsor in attacks. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "Repulsor",
	},
	
	{
		Name = "BattleshipDroneSpeed",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 250,
		Time = 40,
		DisplayedName = "-20% Battleship Drone Build Time",
		DisplayPriority = 1204,
		Description = "<b>Description:</b> Allows Battleship to Build drones 20% Faster. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Battleship",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Build,
		ShortDisplayedName = "-20% Drone Time",
	},
		--Destroyer Upgrades
	{
		Name = "DestroyerHealthUpgrade1",
		RequiredResearch = "DestroyerTech",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 60,
		DisplayedName = "+10% Destroyer Health",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Destroyer Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Destroyer",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		ShortDisplayedName = "+10% Health",
		Icon = Icon_Health,
	},
	{
		Name = "DestroyerHealthUpgrade2",
		RequiredResearch = "DestroyerHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 1500,
		Time = 75,
		DisplayedName = "+5% Destroyer Health",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Destroyer Hulls by an additional 5%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Destroyer",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	
	{
		Name = "DestroyerMAXSPEEDUpgrade1",
		RequiredResearch = "DestroyerTech",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 30,
		DisplayedName = "+20% Destroyer Speed",
		DisplayPriority = 406,
		Description = "<b>Description:</b> Improves Destroyer conventional drive systems by 20%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Destroyer",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "+20% MaxSpeed",
	},
	{
		Name = "DestroyerMAXSPEEDUpgrade2",
		RequiredResearch = "DestroyerMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		Cost = 1500,
		Time = 40,
		DisplayedName = "+10% Destroyer Speed",
		DisplayPriority = 406,
		Description = "<b>Description:</b> Improves Destroyer conventional drive systems by an additional 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Destroyer",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.3,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	
	{
		Name = "DestroyerWeaponUpgrade1",
		RequiredResearch = "DestroyerTech",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 100,
		DisplayedName = "+10% Destroyer Weapons",
		DisplayPriority = 407,
		Description = "<b>Description:</b> Improves Destroyer Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Destroyer",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.12,
		Icon = Icon_Tech,
		ShortDisplayedName = "+12% Weapons",
	},
	{
		Name = "DestroyerWeaponUpgradePartTwo",
		RequiredResearch = "DestroyerWeaponUpgrade1",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = " ",
		DisplayPriority = 407,
		Description = " ",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Destroyer",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.12,
		Icon = Icon_Tech,
		ShortDisplayedName = " ",
	},
	--Crossbow Upgrades
	{
		Name = "CrossbowHealthUpgrade1",
		RequiredResearch = "LightCruisers",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 750,
		Time = 30,
		DisplayedName = "+10% Light Cruiser Health",
		DisplayPriority = 407,
		Description = "<b>Description:</b> Improves Light Cruiser Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_Crossbow_Cruiser",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "CrossbowHealthUpgrade2",
		RequiredResearch = "CrossbowHealthUpgrade1",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 60,
		DisplayedName = "+5% Light Cruiser Health",
		DisplayPriority = 407,
		Description = "<b>Description:</b> Improves Light Cruiser Hulls by an additional 5%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_Crossbow_Cruiser",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	{
		Name = "CrossbowMAXSPEEDUpgrade1",
		RequiredResearch = "LightCruisers",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 30,
		DisplayedName = "+10% Light Cruiser Speed",
		DisplayPriority = 408,
		Description = "<b>Description:</b> Improves Light Cruiser conventional drive systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_Crossbow_Cruiser",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.1,
		Icon = Icon_Speed,
		ShortDisplayedName = "+10% MaxSpeed",
	},
	{
		Name = "CrossbowMAXSPEEDUpgrade2",
		RequiredResearch = "LightCruisers",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 1000,
		Time = 30,
		DisplayedName = "Crossbow Engine 2",
		DisplayPriority = 408,
		Description = "<b>Description:</b> Improves Light Cruiser conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_Crossbow_Cruiser",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.15,
		Icon = Icon_Speed,
		ShortDisplayedName = "Lvl 2 Crossbow",
	},
	
	{
		Name = "CrossbowWeaponUpgrade",
		RequiredResearch = "LightCruisers",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		Cost = 900,
		Time = 45,
		DisplayedName = "+10% Light Cruiser Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Light Cruiser Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_Crossbow_Cruiser",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Weapons",
	},
	{
		Name = "CrossbowWeaponUpgradePartTwo",
		RequiredResearch = "CrossbowWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "+10% Light Cruiser Weapons",
		DisplayPriority = 405,
		Description = "<b>Description:</b> Improves Battleship Weapon systems by 10%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "hgn_Crossbow_Cruiser",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "+10% Weapons",
	},
	--Factory Upgrades
	{
		Name = "ShipyardHealthUpgrade1",
		RequiredResearch = "SCENABLED",
		RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
		Cost = 750,
		Time = 30,
		DisplayedName = "+10% Factory Health",
		DisplayPriority = 1200,
		Description = "<b>Description:</b> Improves Factory Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module, Capital Ship Facility and Slipstream Module.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Shipyard",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "ShipyardHealthUpgrade2",
		RequiredResearch = "ShipyardHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & Hyperspace",
		Cost = 1500,
		Time = 40,
		DisplayedName = "+5% Factory Health",
		DisplayPriority = 1200,
		Description = "<b>Description:</b> Improves Factory Hulls by an additional 5%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module, Capital Ship Facility and Slipstream Module.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Shipyard",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+5% Health",
	},
	{
		Name = "ShipyardMAXSPEEDUpgrade1",
		RequiredResearch = "SCENABLED",
		RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
		Cost = 1500,
		Time = 60,
		DisplayedName = "+20% Factory Speed",
		DisplayPriority = 1203,
		Description = "<b>Description:</b> Improves Factory conventional drive systems by 20%. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Shipyard",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Speed,
		ShortDisplayedName = "+20% MaxSpeed",
	},
	{
		Name = "ShipyardBUILDSPEEDUpgrade1",
		RequiredResearch = "SCENABLED",
		RequiredSubSystems = "AdvancedResearch & Hyperspace",
		Cost = 1000,
		Time = 40,
		DisplayedName = "-20% Factory Build Time",
		DisplayPriority = 1204,
		Description = "<b>Description:</b> Allows Factory to Build Ships 20% Faster. \n\n<b>Prerequisites:</b> Technology I Module and Capital Ship Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_Shipyard",
		UpgradeName = "BUILDSPEED",
		UpgradeValue = 1.2,
		Icon = Icon_Build,
		ShortDisplayedName = "-20% Build Time",
	},
	
	{
		Name = "ShipyardUsePing",
		RequiredResearch = "SCENABLED",
		RequiredSubSystems = "AdvancedResearch & Hyperspace & AdvancedArray |  CloakSensor | HyperspaceSensor",
		Cost = 550,
		Time = 30,
		DisplayedName = "Factory Sensors Ping",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Factory to Ping Targets. \n\n<b>Prerequisites:</b> Technology I Module and Sensors Module.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_Shipyard",
		UpgradeName = "SensorPing", 
		Icon = Icon_Ability,
		ShortDisplayedName = "Sensors Ping",
	},
	
	--Gun Platform Upgrades
	{
		Name = "GunTurretHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		Cost = 500,
		Time = 30,
		DisplayedName = "+10% Gun Platform Health",
		DisplayPriority = 600,
		Description = "<b>Description:</b> Improves Gun Platform Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_GunTurret",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "GunTurretHealthUpgrade2",
		RequiredResearch = "GunTurretHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & PlatformProduction",
		Cost = 800,
		Time = 40,
		DisplayedName = "+6% Gun Platform Health",
		DisplayPriority = 600,
		Description = "<b>Description:</b> Improves Gun Platform Hulls by an additional 6%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_GunTurret",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.16,
		Icon = Icon_Health,
		ShortDisplayedName = "+6% Health",
	},
	{
		Name = "GunTurretWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+8% Gun Turret Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Gun Turret Weapon systems by 8%. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_GunTurret",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "+8% Weapons",
	},
	{
		Name = "GunTurretWeaponUpgradePartTwo",
		RequiredResearch = "GunTurretWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_GunTurret",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Pulsar Platform
	{
		Name = "PulsarPlatformHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		Cost = 500,
		Time = 30,
		DisplayedName = "+10% Pulsar Platform Health",
		DisplayPriority = 600,
		Description = "<b>Description:</b> Improves Pulsar Platform Hulls by 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarPlatform",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.1,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	{
		Name = "PulsarPlatformHealthUpgrade2",
		RequiredResearch = "PulsarPlatformHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch & PlatformProduction",
		Cost = 800,
		Time = 40,
		DisplayedName = "+6% Pulsar PlatformHealth",
		DisplayPriority = 600,
		Description = "<b>Description:</b> Improves Pulsar Platform Hulls by an additional 6%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarPlatform",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.16,
		Icon = Icon_Health,
		ShortDisplayedName = "+6% Health",
	},
	{
		Name = "PulsarPlatformWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+8% Pulsar Platform Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Pulsar Platform Weapon systems by 8%. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarPlatform",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "+8% Weapons",
	},
	{
		Name = "PulsarPlatformWeaponUpgradePartTwo",
		RequiredResearch = "PulsarPlatformWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_PulsarPlatform",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Ion Platfom Upgrades
	{
		Name = "IonTurretHealthUpgrade1",
		RequiredResearch = "PlatformIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		Cost = 500,
		Time = 30,
		DisplayedName = "+9% Ion Turret Health",
		DisplayPriority = 603,
		Description = "<b>Description:</b> Improves Ion Platform Hulls by 9%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonTurret",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.09,
		Icon = Icon_Health,
		ShortDisplayedName = "+9% Health",
	},
	{
		Name = "IonTurretHealthUpgrade2",
		RequiredResearch = "IonTurretHealthUpgrade1 & PlatformIonWeapons",
		RequiredSubSystems = "AdvancedResearch & PlatformProduction",
		Cost = 800,
		Time = 40,
		DisplayedName = "+4% Ion Turret Health",
		DisplayPriority = 603,
		Description = "<b>Description:</b> Improves Ion Platform Hulls by 4%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonTurret",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.13,
		Icon = Icon_Health,
		ShortDisplayedName = "+4% Health",
	},
	{
		Name = "IonTurretWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		Cost = 1000,
		Time = 75,
		DisplayedName = "+8% Ion Turret Weapons",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Ion Turret Weapon systems by 8%. \n\n<b>Prerequisites:</b> Technology I Module and Platform Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonTurret",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "+8% Weapons",
	},
	{
		Name = "GunTurretWeaponUpgradePartTwo",
		RequiredResearch = "GunTurretWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_IonTurret",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.08,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	--Resource Collector Upgrades
	{
		Name = "ResourceCollectorHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 400,
		Time = 40,
		DisplayedName = "+20% Resource Collector Health",
		DisplayPriority = 701,
		Description = "<b>Description:</b> Improves Resource Collector Hulls by 20%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceCollector",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.2,
		Icon = Icon_Health,
		ShortDisplayedName = "+20% Health",
	},
	{
		Name = "ResourceCollectorHealthUpgrade2",
		RequiredResearch = "ResourceCollectorHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch",
		Cost = 800,
		Time = 60,
		DisplayedName = "+10% Resource Collector Health",
		DisplayPriority = 701,
		Description = "<b>Description:</b> Improves Resource Collector Hulls by an Additional 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceCollector",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.30,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	
	{
		Name = "ResourceCollectorMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 300,
		Time = 30,
		DisplayedName = "+5% Resource Collector Speed",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Resource Collector conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceCollector",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.05,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "ResourceCollectorMAXSPEEDUpgrade2",
		RequiredResearch = "ResourceCollectorMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch",
		Cost = 500,
		Time = 40,
		DisplayedName = "+5% Resource Collector Speed II",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Resource Collector conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceCollector",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed II",
	},
	
	{
		Name = "RepairAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 750,
		Time = 40,
		DisplayedName = "$7511",
		DisplayPriority = 26,
		Description = "$7512",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_ResourceCollector",
		UpgradeName = "Repair",
		Icon = Icon_Ability,
		ShortDisplayedName = "$7205",
	},
	--Resource Controller Upgrades
	{
		Name = "ResourceControllerHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 500,
		Time = 30,
		DisplayedName = "+15% Resource Controller Health",
		DisplayPriority = 704,
		Description = "<b>Description:</b> Improves Resource Controller Hulls by 15%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.15,
		Icon = Icon_Health,
		ShortDisplayedName = "+15% Health",
	},
	{
		Name = "ResourceControllerHealthUpgrade2",
		RequiredResearch = "ResourceControllerHealthUpgrade1",
		RequiredSubSystems = "AdvancedResearch",
		Cost = 1000,
		Time = 40,
		DisplayedName = "+10% Resource Controller Health",
		DisplayPriority = 704,
		Description = "<b>Description:</b> Improves Resource Controller Hulls by an additional 10%, allowing them to withstand more damage. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1.25,
		Icon = Icon_Health,
		ShortDisplayedName = "+10% Health",
	},
	
	{
		Name = "ResourceControllerMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 300,
		Time = 30,
		DisplayedName = "+5% Resource Controller Speed",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Resource Controller conventional drive systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.05,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed",
	},
	{
		Name = "ResourceControllerMAXSPEEDUpgrade2",
		RequiredResearch = "ResourceControllerMAXSPEEDUpgrade1",
		RequiredSubSystems = "AdvancedResearch",
		Cost = 500,
		Time = 40,
		DisplayedName = "+5% Resource Controller Speed II",
		DisplayPriority = 81,
		Description = "<b>Description:</b> Improves Resource Controller conventional drive systems by an additional 5%. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "MAXSPEED",
		UpgradeValue = 1.10,
		Icon = Icon_Speed,
		ShortDisplayedName = "+5% MaxSpeed II",
	},
	
	{
		Name = "ResourceControllerWeaponUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 500,
		Time = 60,
		DisplayedName = "+5% Resource Controller Defense",
		DisplayPriority = 83,
		Description = "<b>Description:</b> Improves Resource Controller defense systems by 5%. \n\n<b>Prerequisites:</b> Technology I Module.",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.05,
		Icon = Icon_Tech,
		ShortDisplayedName = "+5% Defense",
	},
	{
		Name = "ResourceControllerWeaponUpgradePartTwo",
		RequiredResearch = "ResourceControllerWeaponUpgrade",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "",
		DisplayPriority = 405,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "WeaponAccuracy",
		UpgradeValue = 1.1,
		Icon = Icon_Tech,
		ShortDisplayedName = "",
	},
	
	{
		Name = "ResourceControllerUseLasers",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		Cost = 550,
		Time = 30,
		DisplayedName = "Resource Controller Defense Lasers",
		DisplayPriority = 30,
		Description = "<b>Description:</b> Allows Resource Controller to use Defense Lasers. \n\n<b>Prerequisites:</b> Technology I Module and Fighter Facility.",
		UpgradeType = Ability,
		TargetType = Ship,
		TargetName = "Hgn_ResourceController",
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		Icon = Icon_Ability,
		ShortDisplayedName = "Defense Lasers",
	},
	--Homeworld 2 Single Player Hacks
	{
		Name = "SensorsDowngrade1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Sensors Downgrade1",
		DisplayPriority = 1210,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MotherShip",
		UpgradeName = "PrimarySensorsRange",
		UpgradeValue = 0.3,
	},
	{
		Name = "SensorsDowngrade2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Sensors Downgrade2",
		DisplayPriority = 1211,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MotherShip",
		UpgradeName = "SecondarySensorsRange",
		UpgradeValue = 0.3,
	},
	{
		Name = "SensorsDowngrade3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Sensors Downgrade3",
		DisplayPriority = 1212,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MotherShip",
		UpgradeName = "VisualRange",
		UpgradeValue = 0.3,
	},
	{
		Name = "SensorsBackToNormal1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "SensorsBackToNormal1",
		DisplayPriority = 1213,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MotherShip",
		UpgradeName = "PrimarySensorsRange",
		UpgradeValue = 1,
	},
	{
		Name = "SensorsBackToNormal2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "SensorsBackToNormal2",
		DisplayPriority = 1214,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MotherShip",
		UpgradeName = "SecondarySensorsRange",
		UpgradeValue = 1,
	},
	{
		Name = "SensorsBackToNormal3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "SensorsBackToNormal3",
		DisplayPriority = 1215,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_MotherShip",
		UpgradeName = "VisualRange",
		UpgradeValue = 1,
	},
	{
		Name = "AssaultCorvetteEliteWeaponUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Elite Assault Corvette Weapon Upgrade",
		DisplayPriority = 1204,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AssaultCorvetteElite",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 2,
	},
	{
		Name = "AttackBomberEliteWeaponUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Elite Attack Bomber Weapon Upgrade",
		DisplayPriority = 1205,
		Description = "",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Hgn_AttackBomberElite",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.8,
	},
	{
		Name = "MoverHealthUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Mover health upgrade",
		DisplayPriority = 41,
		Description = "Upgrades Mover health",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_Mover",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 5,
	},
	{
		Name = "MoverHealthDowngrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Mover health downgrade",
		DisplayPriority = 41,
		Description = "Downgrades Mover health",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_Mover",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 1,
	},
	{
		Name = "FrigateHealthUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 800,
		Time = 60,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Family,
		TargetName = "Frigate",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 2.5,
	},
	{
		Name = "KeeperHealthUpgradeSPGAME_LOW",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_Destroyer",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 2.5,
	},
	{
		Name = "KeeperHealthUpgradeSPGAME_MED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_Destroyer",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3.5,
	},
	{
		Name = "KeeperHealthUpgradeSPGAME_HIGH",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_Destroyer",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 4.5,
	},
	{
		Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.1,
	},
	{
		Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.2,
	},
	{
		Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.3,
	},
	{
		Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_4",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.4,
	},
	{
		Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_5",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.5,
	},
	{
		Name = "KeeperWeaponUpgradeSPGAME_M10_LVL_6",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 0.6,
	},
	{
		Name = "KeeperHealthUpgradeSPGAME_M10_LVL_1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 2,
	},
	{
		Name = "KeeperHealthUpgradeSPGAME_M10_LVL_2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3,
	},
	{
		Name = "KeeperHealthUpgradeSPGAME_M10_LVL_3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_DestroyerM10",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 4,
	},
	{
		Name = "AttackDroidHealthUpgradeSPGAME_LOW",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_AttackDroid",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 2,
	},
	{
		Name = "AttackDroidHealthUpgradeSPGAME_MED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_AttackDroid",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 3,
	},
	{
		Name = "AttackDroidHealthUpgradeSPGAME_HIGH",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_AttackDroid",
		UpgradeName = "MAXHEALTH",
		UpgradeValue = 4,
	},
	{
		Name = "AttackDroidWeaponUpgradeSPGAME_LOW",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_AttackDroid",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.3,
	},
	{
		Name = "AttackDroidWeaponUpgradeSPGAME_MED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_AttackDroid",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 1.6,
	},
	{
		Name = "AttackDroidWeaponUpgradeSPGAME_HIGH",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "$7571",
		DisplayPriority = 300,
		Description = "$7572",
		UpgradeType = Modifier,
		TargetType = Ship,
		TargetName = "Kpr_AttackDroid",
		UpgradeName = "WeaponDamage",
		UpgradeValue = 2,
	},
	{
		Name = "SCENABLED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		Cost = 0,
		Time = 0,
		DisplayedName = "Instant Tech!!!!!!!!!!!!!!!!!!!!!!!!!!",
		DisplayPriority = 1,
		Description = "",
		TargetName = "Hgn_Shipyard",
	},	
}
