-- UC_ file
-- Generated by Nick Waanders

-- UC_ file
-- Generated by Nick Waanders

--
UC_Family("Fighter", 250);

--
UC_Family("Corvette", 250);

--
UC_Family("Frigate", 300);

--
UC_Family("Capital", 250);
	
--
UC_Family("Utility", 500);

--
UC_Family("Platform", 250);

--
UC_Family("Mothership", 60);

UC_Family("SinglePlayerMisc", 1000);


