-- Camera Settings --

cameraDefaultMaxDistance = 6000
cameraDistanceMax = 6000
cameraDistanceMin = 20
cameraDragRotateScalar = 120
cameraDragZoomScalar = 3
cameraFloatAmplitude =  { 0.15, 0.15, }
cameraFloatDistanceFactor = 0.005
cameraFloatEnableTime = 3
cameraFloatFrequency = 0.2
cameraFloatShape = 2
cameraMaxDeclination = deg((PI * 0.5 - 0.01))
cameraMinDeclination = deg(-((PI * 0.5 - 0.01)))
cameraMouseWheelEvalThreshold = 0.001
cameraMouseWheelTrackingTimeSteps = 240
cameraMouseWheelZoomTrack = 0.05
cameraTrackingAngleSpeedAuto = 0.05
cameraTrackingAngleSpeedUser = 0.1
cameraTrackingPositionBase = 2
cameraTrackingPositionSpeed = 0.02
cameraTrackingPositionThreshold = 0.2
cameraTrackingTimeSteps = 240
cameraTwkMaxPanSpeed = 10000000
cameraTwkMinPanSpeed = 0
cameraTwkPanAccelCurve = 1
cameraTwkPanAccelTime = 6
cameraTwkPanDecelTime = 3
cameraTwkPanSpeedFactor = 1
cameraTwkPanUnderFactor = 0.3
cameraTwkPanUnfocussedDist = 1000
cameraZoomDecel = 0.4
cameraZoomFactor = 2.15
farClip = 440000
farClipCullFactor = 0.9
nearClip = 3
panHorizontalZone = 2.5 / 1024
panModel = PAN_VerticalGoesForwardLocked
panModifierAction = PMA_UpWorld
panModifierKey = 18
panVerticalZone = 2.5 / 1024
retainDistanceFocusCloser = 1
retainDistanceFocusFarther = 1
verticalFOV = 80

CAM_CUBIC_EVAL_ANGLE_TWEAK = 2
CAM_CUBIC_EVAL_TWEAK = 3
MAX_CAMERA_STACKS = 40
RENDER_VIEWABLE_DISTANCE_MAX_SQR = 400000 * 400000
RENDER_VIEWABLE_DISTANCE_MIN_SQR = 0
RENDER_VIEWABLE_DISTANCE_SM_SQR = 300500 * 300500
RENDER_VIEWABLE_DISTANCE_SQR = 300500 * 300500
